/**
 * Atlas Ingest Service — server-side helpers for the admin ingest UI.
 *
 * Provides:
 *   - Filename parsing (mfr_{ID}_{ENGLISH}_{CHINESE}_params.json → metadata)
 *   - New-MFR detection against atlas_manufacturers
 *   - Wrapper for shelling out to scripts/atlas-ingest.mjs
 *
 * Design note: the heavy lifting (mapping, classification, diff, snapshot/upsert)
 * lives in scripts/atlas-ingest.mjs. API routes shell out to that script to avoid
 * duplicating ~600 lines of mapping logic in TypeScript. This module is the
 * thin TS-side wrapper.
 */

import { spawn } from 'child_process';
import { resolve } from 'path';
import type { SupabaseClient } from '@supabase/supabase-js';

// ─── Types shared with the UI ────────────────────────────

export type IngestRisk = 'clean' | 'review' | 'attention';
export type IngestStatus = 'pending' | 'applied' | 'reverted' | 'expired';

export type IngestDiffReport = {
  manufacturer: string;
  sourceFile: string;
  sourceFileSha256: string;
  productCounts: {
    inNewFile: number;
    inDb: number;
    willInsert: number;
    willUpdate: number;
    willDelete: number;
  };
  attrChanges: {
    totalNewAttrs: number;
    totalChangedValues: number;
    totalRemovedAttrs: number;
    perProduct: Array<{
      mpn: string;
      kind: 'insert' | 'update';
      added: string[];
      changed: Array<{ key: string; oldValue: unknown; newValue: unknown }>;
      removed: string[];
      classification?: Array<{ field: string; oldValue: unknown; newValue: unknown }>;
    }>;
  };
  classificationChanges: Array<{ mpn: string; field: string; oldValue: unknown; newValue: unknown }>;
  deletes: Array<{ mpn: string; kind: 'hard_delete' | 'soft_delete'; reason: string }>;
  attrCountStats: { avgBefore: number; avgAfter: number };
  unmappedParams: Array<{
    paramName: string;
    sampleValues: string[];
    productCount: number;
    attributeId: string;
    kind: 'gaia' | 'standard';
  }>;
  familyCounts: Record<string, number>;
  mappingStats: { total: number; mapped: number; errors: number };
};

export type IngestBatch = {
  batch_id: string;
  manufacturer: string;
  source_file: string;
  source_file_sha256: string;
  report: IngestDiffReport;
  status: IngestStatus;
  risk: IngestRisk;
  created_at: string;
  applied_at: string | null;
  applied_by: string | null;
  reverted_at: string | null;
  reverted_by: string | null;
};

export type ParsedFilename = {
  filename: string;
  atlasId: number | null;
  nameEn: string | null;
  nameZh: string | null;
  nameDisplay: string | null;
  slug: string | null;
};

export type StagedFile = {
  filename: string;
  filePath: string;
  sizeBytes: number;
  parsed: ParsedFilename;
  isNewManufacturer: boolean;
  existingManufacturer: {
    atlas_id: number;
    name_display: string;
    slug: string;
  } | null;
};

// ─── Filename parser ─────────────────────────────────────

const FILENAME_REGEX = /^mfr_(\d+)_(.+?)_(.+?)_params\.json$/;

/**
 * Parses an atlas manufacturer JSON filename like
 *   mfr_4_GIGADEVICE_兆易创新_params.json
 * into structured fields. Returns nulls for fields that can't be parsed.
 *
 * Slug is generated by lowercasing the English name and replacing
 * non-alphanumeric runs with hyphens (mirrors the convention used by
 * scripts/atlas-manufacturers-import.mjs).
 */
export function parseAtlasFilename(filename: string): ParsedFilename {
  const match = FILENAME_REGEX.exec(filename);
  if (!match) {
    return { filename, atlasId: null, nameEn: null, nameZh: null, nameDisplay: null, slug: null };
  }
  const atlasId = parseInt(match[1], 10);
  const nameEn = match[2].trim();
  const nameZh = match[3].trim();
  const nameDisplay = `${nameEn} ${nameZh}`;
  const slug = nameEn
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return { filename, atlasId, nameEn, nameZh, nameDisplay, slug };
}

// ─── New-MFR detection ───────────────────────────────────
//
// The filename's atlas_id (e.g. mfr_209_*) is the data team's source identifier
// and does NOT necessarily match atlas_manufacturers.atlas_id, which was
// populated from a master list Excel and uses a different ID space (e.g. 700182).
//
// Match priority: name_display (exact) → atlas_id (filename-parsed) → name_en
// (case-insensitive) → slug. First match wins.

type MfrRow = { atlas_id: number | null; name_display: string; name_en: string | null; slug: string };

export type ManufacturerLookup = {
  byNameDisplay: Map<string, MfrRow>;
  byAtlasId: Map<number, MfrRow>;
  byNameEnLower: Map<string, MfrRow>;
  bySlug: Map<string, MfrRow>;
};

export async function loadManufacturerLookup(supabase: SupabaseClient): Promise<ManufacturerLookup> {
  const byNameDisplay = new Map<string, MfrRow>();
  const byAtlasId = new Map<number, MfrRow>();
  const byNameEnLower = new Map<string, MfrRow>();
  const bySlug = new Map<string, MfrRow>();

  let from = 0;
  const PAGE = 1000;
  while (true) {
    const { data, error } = await supabase
      .from('atlas_manufacturers')
      .select('atlas_id, name_display, name_en, slug')
      .range(from, from + PAGE - 1);
    if (error) throw new Error(`loadManufacturerLookup: ${error.message}`);
    if (!data || data.length === 0) break;
    for (const row of data as MfrRow[]) {
      if (row.name_display) byNameDisplay.set(row.name_display, row);
      if (row.atlas_id != null) byAtlasId.set(row.atlas_id, row);
      if (row.name_en) byNameEnLower.set(row.name_en.toLowerCase(), row);
      if (row.slug) bySlug.set(row.slug, row);
    }
    if (data.length < PAGE) break;
    from += PAGE;
  }
  return { byNameDisplay, byAtlasId, byNameEnLower, bySlug };
}

export function buildStagedFile(
  filename: string,
  filePath: string,
  sizeBytes: number,
  lookup: ManufacturerLookup,
): StagedFile {
  const parsed = parseAtlasFilename(filename);
  // Match priority: name_display → atlas_id → name_en (case-insensitive) → slug.
  // First hit wins. Returning the matched row's identity (not the parsed identity)
  // lets the UI tell the user which existing record was matched.
  let existing: MfrRow | null = null;
  if (parsed.nameDisplay && lookup.byNameDisplay.has(parsed.nameDisplay)) {
    existing = lookup.byNameDisplay.get(parsed.nameDisplay) ?? null;
  } else if (parsed.atlasId != null && lookup.byAtlasId.has(parsed.atlasId)) {
    existing = lookup.byAtlasId.get(parsed.atlasId) ?? null;
  } else if (parsed.nameEn && lookup.byNameEnLower.has(parsed.nameEn.toLowerCase())) {
    existing = lookup.byNameEnLower.get(parsed.nameEn.toLowerCase()) ?? null;
  } else if (parsed.slug && lookup.bySlug.has(parsed.slug)) {
    existing = lookup.bySlug.get(parsed.slug) ?? null;
  }

  return {
    filename,
    filePath,
    sizeBytes,
    parsed,
    isNewManufacturer: !existing,
    existingManufacturer: existing
      ? { atlas_id: existing.atlas_id ?? 0, name_display: existing.name_display, slug: existing.slug }
      : null,
  };
}

// ─── Spawn wrapper for atlas-ingest.mjs ──────────────────

export type ScriptResult = {
  exitCode: number;
  stdout: string;
  stderr: string;
};

/**
 * Runs `node scripts/atlas-ingest.mjs <args>` and captures output.
 * Inherits the parent process's env (Supabase keys, etc.).
 *
 * Caller is responsible for parsing stdout when structured data is needed
 * (e.g., extracting batch IDs from --report output).
 */
export function runIngestScript(args: string[]): Promise<ScriptResult> {
  return new Promise((resolveSpawn, rejectSpawn) => {
    const cwd = process.cwd();
    const scriptPath = resolve(cwd, 'scripts/atlas-ingest.mjs');
    const child = spawn('node', [scriptPath, ...args], {
      cwd,
      env: { ...process.env },
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => { stdout += chunk.toString(); });
    child.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
    child.on('error', (err) => rejectSpawn(err));
    child.on('close', (code) => {
      resolveSpawn({ exitCode: code ?? 0, stdout, stderr });
    });
  });
}

// ─── Markdown report path resolver ───────────────────────

/**
 * Markdown reports are written by the script to /tmp/atlas-report-<safeName>-<batchId-prefix>.md.
 * The prefix is the first 8 chars of the batch UUID. This helper rebuilds the path.
 */
export function markdownReportPath(manufacturer: string, batchId: string, outDir = '/tmp'): string {
  const safeName = manufacturer.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40);
  return `${outDir}/atlas-report-${safeName}-${batchId.slice(0, 8)}.md`;
}
