// GENERATED FILE — DO NOT EDIT.
// Source of truth: docs/min_attr_sets.md
// Regenerate:      npm run selection:audit
//
// Hand-editing this file re-creates the bug it exists to prevent: a code copy of the
// selection questions that is allowed to drift from the document describing them.

import type { SelectionState } from './selectionDoc';

export interface GeneratedSelectionEntry {
  state: SelectionState;
  reason?: string;
}

/** familyId → attributeId → state. Every scored rule in every family appears here. */
export const SELECTION_STATES: Record<string, Record<string, GeneratedSelectionEntry>> = {
  '12': {
    "capacitance": { state: 'required' },
    "package_case": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "dielectric": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "flexible_termination": { state: 'narrows' },
    "operating_temp": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "dc_bias_derating": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "esr": { state: 'not_asked' },
    "esl": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '13': {
    "capacitance": { state: 'required' },
    "package_case": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "dielectric": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "temperature_coefficient": { state: 'narrows' },
    "operating_temp": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "esr": { state: 'not_asked' },
    "esl": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '52': {
    "resistance": { state: 'required' },
    "package_case": { state: 'required' },
    "power_rating": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "tcr": { state: 'narrows' },
    "voltage_rated": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "anti_sulfur": { state: 'not_asked' },
    "composition": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '53': {
    "resistance": { state: 'required' },
    "mounting_style": { state: 'required' },
    "lead_spacing": { state: 'required' },
    "power_rating": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "composition": { state: 'narrows' },
    "package_case": { state: 'not_asked' },
    "voltage_rated": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "anti_sulfur": { state: 'not_asked' },
    "tcr": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "body_dimensions": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '54': {
    "resistance": { state: 'required' },
    "package_case": { state: 'required' },
    "power_rating": { state: 'required' },
    "kelvin_sensing": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "tcr": { state: 'narrows' },
    "voltage_rated": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "anti_sulfur": { state: 'not_asked' },
    "power_rating_pulse": { state: 'not_asked' },
    "composition": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "parasitic_inductance": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '55': {
    "resistance": { state: 'required' },
    "power_rating": { state: 'required' },
    "mounting_style": { state: 'required' },
    "heatsink_dimensions": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "thermal_resistance": { state: 'narrows' },
    "package_case": { state: 'not_asked' },
    "voltage_rated": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "anti_sulfur": { state: 'not_asked' },
    "tcr": { state: 'not_asked' },
    "composition": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '58': {
    "capacitance": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "polarization": { state: 'required' },
    "mounting_type": { state: 'required' },
    "diameter": { state: 'required' },
    "lead_spacing": { state: 'required' },
    "esr": { state: 'narrows' },
    "ripple_current": { state: 'narrows' },
    "lifetime": { state: 'narrows' },
    "aec_q200": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "tolerance": { state: 'not_asked' },
    "impedance": { state: 'not_asked' },
    "leakage_current": { state: 'not_asked' },
    "capacitor_type": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '59': {
    "capacitance": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "package_case": { state: 'required' },
    "capacitor_type": { state: 'required' },
    "esr": { state: 'narrows' },
    "failure_mode": { state: 'narrows' },
    "aec_q200": { state: 'not_asked' },
    "ripple_current": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "tolerance": { state: 'not_asked' },
    "surge_voltage": { state: 'not_asked' },
    "dc_bias_derating": { state: 'not_asked' },
    "leakage_current": { state: 'not_asked' },
    "dissipation_factor": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '60': {
    "capacitance": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "polarization": { state: 'required' },
    "mounting_type": { state: 'required' },
    "esr": { state: 'required' },
    "ripple_current": { state: 'narrows' },
    "tolerance": { state: 'narrows' },
    "aec_q200": { state: 'not_asked' },
    "lead_spacing": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "diameter": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "impedance": { state: 'not_asked' },
    "leakage_current": { state: 'not_asked' },
    "polymer_type": { state: 'not_asked' },
    "capacitor_type": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '61': {
    "capacitance": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "package_case": { state: 'required' },
    "esr": { state: 'required' },
    "leakage_current": { state: 'narrows' },
    "peak_current": { state: 'narrows' },
    "aec_q200": { state: 'not_asked' },
    "technology": { state: 'not_asked' },
    "cycle_life": { state: 'not_asked' },
    "lifetime": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "self_discharge": { state: 'not_asked' },
    "diameter": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "cap_aging": { state: 'not_asked' },
    "esr_aging": { state: 'not_asked' },
    "tolerance": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '64': {
    "capacitance": { state: 'required' },
    "package_case": { state: 'required' },
    "lead_spacing": { state: 'required' },
    "voltage_rated_dc": { state: 'required' },
    "safety_rating": { state: 'required' },
    "voltage_rated_ac": { state: 'narrows' },
    "tolerance": { state: 'narrows' },
    "dielectric_type": { state: 'narrows' },
    "aec_q200": { state: 'not_asked' },
    "self_healing": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "flammability": { state: 'not_asked' },
    "dv_dt": { state: 'not_asked' },
    "ripple_current": { state: 'not_asked' },
    "dissipation_factor": { state: 'not_asked' },
    "esr": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "body_length": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '65': {
    "varistor_voltage": { state: 'required' },
    "max_continuous_voltage": { state: 'required' },
    "package_case": { state: 'required' },
    "energy_rating": { state: 'narrows' },
    "peak_surge_current": { state: 'narrows' },
    "safety_rating": { state: 'narrows' },
    "clamping_voltage": { state: 'not_asked' },
    "thermal_disconnect": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "lead_spacing": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "disc_diameter": { state: 'not_asked' },
    "surge_pulse_lifetime": { state: 'not_asked' },
    "response_time": { state: 'not_asked' },
    "leakage_current": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '66': {
    "hold_current": { state: 'required' },
    "max_voltage": { state: 'required' },
    "trip_current": { state: 'required' },
    "package_case": { state: 'required' },
    "initial_resistance": { state: 'narrows' },
    "time_to_trip": { state: 'narrows' },
    "max_fault_current": { state: 'not_asked' },
    "safety_rating": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "endurance_cycles": { state: 'not_asked' },
    "post_trip_resistance": { state: 'not_asked' },
    "power_dissipation": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '67': {
    "resistance_r25": { state: 'required' },
    "b_value": { state: 'required' },
    "package_case": { state: 'required' },
    "r25_tolerance": { state: 'narrows' },
    "b_value_tolerance": { state: 'narrows' },
    "rt_curve": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "interchangeability": { state: 'not_asked' },
    "max_power": { state: 'not_asked' },
    "thermal_time_constant": { state: 'not_asked' },
    "dissipation_constant": { state: 'not_asked' },
    "application_category": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '68': {
    "resistance_r25": { state: 'required' },
    "curie_temp": { state: 'required' },
    "package_case": { state: 'required' },
    "trip_current": { state: 'narrows' },
    "hold_current": { state: 'narrows' },
    "rt_curve": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "max_voltage": { state: 'not_asked' },
    "max_current": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "interchangeability": { state: 'not_asked' },
    "r25_tolerance": { state: 'not_asked' },
    "max_power": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '69': {
    "cm_impedance": { state: 'required' },
    "package_case": { state: 'required' },
    "rated_current": { state: 'required' },
    "number_of_lines": { state: 'required' },
    "dcr": { state: 'narrows' },
    "application_type": { state: 'narrows' },
    "cm_inductance": { state: 'not_asked' },
    "impedance_curve": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "voltage_rated": { state: 'not_asked' },
    "interface_compliance": { state: 'not_asked' },
    "safety_rating": { state: 'not_asked' },
    "dm_leakage": { state: 'not_asked' },
    "insulation_voltage": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '70': {
    "impedance_100mhz": { state: 'required' },
    "package_case": { state: 'required' },
    "rated_current": { state: 'required' },
    "dcr": { state: 'narrows' },
    "number_of_lines": { state: 'narrows' },
    "impedance_curve": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "signal_integrity": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "tolerance": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "voltage_rated": { state: 'not_asked' },
    "resistance_type": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '71': {
    "inductance": { state: 'required' },
    "package_case": { state: 'required' },
    "saturation_current": { state: 'required' },
    "rated_current": { state: 'required' },
    "dcr": { state: 'narrows' },
    "shielding": { state: 'narrows' },
    "aec_q200": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "inductance_vs_dc_bias": { state: 'not_asked' },
    "tolerance": { state: 'not_asked' },
    "core_material": { state: 'not_asked' },
    "srf": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "acr": { state: 'not_asked' },
    "construction_type": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  '72': {
    "inductance": { state: 'required' },
    "package_case": { state: 'required' },
    "rated_current": { state: 'required' },
    "srf": { state: 'required' },
    "q_factor": { state: 'narrows' },
    "core_material": { state: 'narrows' },
    "shielding": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "dcr": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "inductance_vs_dc_bias": { state: 'not_asked' },
    "inductance_tolerance": { state: 'not_asked' },
    "tolerance": { state: 'not_asked' },
    "saturation_current": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "acr": { state: 'not_asked' },
    "construction_type": { state: 'not_asked' },
    "msl": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B1': {
    "vrrm": { state: 'required' },
    "io_avg": { state: 'required' },
    "recovery_category": { state: 'required' },
    "configuration": { state: 'required' },
    "package_case": { state: 'required' },
    "vf": { state: 'narrows' },
    "trr": { state: 'narrows' },
    "pin_configuration": { state: 'not_asked' },
    "mounting_style": { state: 'not_asked' },
    "vdc": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "ifsm": { state: 'not_asked' },
    "qrr": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "recovery_behavior": { state: 'not_asked' },
    "rth_jc": { state: 'not_asked' },
    "pd": { state: 'not_asked' },
    "ir_leakage": { state: 'not_asked' },
    "rth_ja": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "cj": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B2': {
    "vrrm": { state: 'required' },
    "io_avg": { state: 'required' },
    "configuration": { state: 'required' },
    "package_case": { state: 'required' },
    "semiconductor_material": { state: 'required' },
    "vf": { state: 'narrows' },
    "ir_leakage": { state: 'narrows' },
    "schottky_technology": { state: 'not_asked' },
    "pin_configuration": { state: 'not_asked' },
    "mounting_style": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "ifsm": { state: 'not_asked' },
    "rth_jc": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "cj": { state: 'not_asked' },
    "rth_ja": { state: 'not_asked' },
    "pd": { state: 'not_asked' },
    "vf_tempco": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "technology_trench_planar": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B3': {
    "vz": { state: 'required' },
    "pd": { state: 'required' },
    "configuration": { state: 'required' },
    "pin_configuration": { state: 'required' },
    "package_case": { state: 'required' },
    "vz_tolerance": { state: 'narrows' },
    "zzt": { state: 'narrows' },
    "mounting_style": { state: 'not_asked' },
    "izt": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "tc": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "izm": { state: 'not_asked' },
    "rth_ja": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "ir_leakage": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "zzk": { state: 'not_asked' },
    "cj": { state: 'not_asked' },
    "vf": { state: 'not_asked' },
    "regulation_type": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B4': {
    "polarity": { state: 'required' },
    "vrwm": { state: 'required' },
    "vc": { state: 'required' },
    "num_channels": { state: 'required' },
    "configuration": { state: 'required' },
    "package_case": { state: 'required' },
    "ppk": { state: 'narrows' },
    "cj": { state: 'narrows' },
    "pin_configuration": { state: 'not_asked' },
    "vbr": { state: 'not_asked' },
    "mounting_style": { state: 'not_asked' },
    "ipp": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "surge_standard": { state: 'not_asked' },
    "esd_rating": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "response_time": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "ir_leakage": { state: 'not_asked' },
    "rth_ja": { state: 'not_asked' },
    "pd": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B5': {
    "channel_type": { state: 'required' },
    "vds_max": { state: 'required' },
    "id_max": { state: 'required' },
    "package_case": { state: 'required' },
    "rds_on": { state: 'narrows' },
    "vgs_th": { state: 'narrows' },
    "pin_configuration": { state: 'not_asked' },
    "technology": { state: 'not_asked' },
    "mounting_style": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "vgs_max": { state: 'not_asked' },
    "qg": { state: 'not_asked' },
    "body_diode_trr": { state: 'not_asked' },
    "id_pulse": { state: 'not_asked' },
    "avalanche_energy": { state: 'not_asked' },
    "qgd": { state: 'not_asked' },
    "coss": { state: 'not_asked' },
    "crss": { state: 'not_asked' },
    "rth_jc": { state: 'not_asked' },
    "soa": { state: 'not_asked' },
    "pd": { state: 'not_asked' },
    "qgs": { state: 'not_asked' },
    "ciss": { state: 'not_asked' },
    "body_diode_vf": { state: 'not_asked' },
    "rth_ja": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B6': {
    "polarity": { state: 'required' },
    "vceo_max": { state: 'required' },
    "ic_max": { state: 'required' },
    "package_case": { state: 'required' },
    "hfe": { state: 'narrows' },
    "vce_sat": { state: 'narrows' },
    "tst": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "vces_max": { state: 'not_asked' },
    "ft": { state: 'not_asked' },
    "toff": { state: 'not_asked' },
    "pd": { state: 'not_asked' },
    "rth_jc": { state: 'not_asked' },
    "soa": { state: 'not_asked' },
    "vbe_sat": { state: 'not_asked' },
    "ton": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B7': {
    "vces_max": { state: 'required' },
    "ic_max": { state: 'required' },
    "package_case": { state: 'required' },
    "co_packaged_diode": { state: 'required' },
    "vce_sat": { state: 'narrows' },
    "eoff": { state: 'narrows' },
    "channel_type": { state: 'not_asked' },
    "igbt_technology": { state: 'not_asked' },
    "mounting_style": { state: 'not_asked' },
    "tsc": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "vge_max": { state: 'not_asked' },
    "eon": { state: 'not_asked' },
    "ic_pulse": { state: 'not_asked' },
    "qg": { state: 'not_asked' },
    "rth_jc": { state: 'not_asked' },
    "soa": { state: 'not_asked' },
    "pd": { state: 'not_asked' },
    "vge_th": { state: 'not_asked' },
    "td_on": { state: 'not_asked' },
    "td_off": { state: 'not_asked' },
    "tf": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "height": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B8': {
    "device_type": { state: 'required' },
    "vdrm": { state: 'required' },
    "on_state_current": { state: 'required' },
    "package_case": { state: 'required' },
    "igt": { state: 'narrows' },
    "ih": { state: 'narrows' },
    "gate_sensitivity": { state: 'not_asked' },
    "quadrant_operation": { state: 'not_asked' },
    "itsm": { state: 'not_asked' },
    "dv_dt": { state: 'not_asked' },
    "i2t": { state: 'not_asked' },
    "il": { state: 'not_asked' },
    "di_dt": { state: 'not_asked' },
    "snubberless": { state: 'not_asked' },
    "vdsm": { state: 'not_asked' },
    "vgt": { state: 'not_asked' },
    "tq": { state: 'not_asked' },
    "rth_jc": { state: 'not_asked' },
    "tgt": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'B9': {
    "channel_type": { state: 'required' },
    "vp": { state: 'required' },
    "idss": { state: 'required' },
    "package_case": { state: 'required' },
    "gfs": { state: 'narrows' },
    "igss": { state: 'narrows' },
    "noise_figure": { state: 'not_asked' },
    "vds_max": { state: 'not_asked' },
    "fc_1f_corner": { state: 'not_asked' },
    "vgs_max": { state: 'not_asked' },
    "ft": { state: 'not_asked' },
    "ciss": { state: 'not_asked' },
    "crss": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
    "pd_max": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "matched_pair_review": { state: 'not_asked' },
  },
  'C1': {
    "output_type": { state: 'required' },
    "polarity": { state: 'required' },
    "output_voltage": { state: 'required' },
    "iout_max": { state: 'required' },
    "package_case": { state: 'required' },
    "vdropout": { state: 'narrows' },
    "output_cap_compatibility": { state: 'narrows' },
    "vin_max": { state: 'not_asked' },
    "enable_pin": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
    "vin_min": { state: 'not_asked' },
    "vout_accuracy": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "psrr": { state: 'not_asked' },
    "power_good": { state: 'not_asked' },
    "thermal_shutdown": { state: 'not_asked' },
    "rth_ja": { state: 'not_asked' },
    "iq": { state: 'not_asked' },
    "load_regulation": { state: 'not_asked' },
    "soft_start": { state: 'not_asked' },
    "line_regulation": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'C2': {
    "topology": { state: 'required' },
    "architecture": { state: 'required' },
    "vin_max": { state: 'required' },
    "vout_range": { state: 'required' },
    "iout_max": { state: 'required' },
    "package_case": { state: 'required' },
    "fsw": { state: 'narrows' },
    "control_mode": { state: 'narrows' },
    "vref": { state: 'narrows' },
    "output_polarity": { state: 'not_asked' },
    "compensation_type": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
    "vin_min": { state: 'not_asked' },
    "ton_min": { state: 'not_asked' },
    "gate_drive_current": { state: 'not_asked' },
    "enable_uvlo": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "soft_start": { state: 'not_asked' },
    "ocp_mode": { state: 'not_asked' },
    "thermal_shutdown": { state: 'not_asked' },
    "rth_ja": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'C3': {
    "driver_configuration": { state: 'required' },
    "isolation_type": { state: 'required' },
    "peak_source_current": { state: 'required' },
    "peak_sink_current": { state: 'required' },
    "vdd_range": { state: 'required' },
    "package_case": { state: 'required' },
    "propagation_delay": { state: 'narrows' },
    "dead_time_control": { state: 'narrows' },
    "output_polarity": { state: 'not_asked' },
    "isolation_voltage": { state: 'not_asked' },
    "input_logic_threshold": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
    "dead_time": { state: 'not_asked' },
    "uvlo": { state: 'not_asked' },
    "tj_max": { state: 'not_asked' },
    "rise_fall_time": { state: 'not_asked' },
    "shutdown_enable": { state: 'not_asked' },
    "bootstrap_diode": { state: 'not_asked' },
    "rth_ja": { state: 'not_asked' },
    "fault_reporting": { state: 'not_asked' },
    "input_vdd_range": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'C4': {
    "device_type": { state: 'required' },
    "channels": { state: 'required' },
    "input_type": { state: 'required' },
    "supply_voltage": { state: 'required' },
    "package_case": { state: 'required' },
    "gain_bandwidth": { state: 'narrows' },
    "vicm_range": { state: 'narrows' },
    "input_bias_current": { state: 'narrows' },
    "output_type": { state: 'not_asked' },
    "rail_to_rail_input": { state: 'not_asked' },
    "rail_to_rail_output": { state: 'not_asked' },
    "min_stable_gain": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
    "slew_rate": { state: 'not_asked' },
    "input_offset_voltage": { state: 'not_asked' },
    "response_time": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "input_noise_voltage": { state: 'not_asked' },
    "output_current": { state: 'not_asked' },
    "avol": { state: 'not_asked' },
    "cmrr": { state: 'not_asked' },
    "psrr": { state: 'not_asked' },
    "iq": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'C5': {
    "logic_function": { state: 'required' },
    "gate_count": { state: 'required' },
    "supply_voltage": { state: 'required' },
    "package_case": { state: 'required' },
    "logic_family": { state: 'narrows' },
    "vih": { state: 'narrows' },
    "tpd": { state: 'narrows' },
    "oe_polarity": { state: 'not_asked' },
    "output_type": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
    "voh": { state: 'not_asked' },
    "drive_current": { state: 'not_asked' },
    "schmitt_trigger": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "vol": { state: 'not_asked' },
    "vil": { state: 'not_asked' },
    "fmax": { state: 'not_asked' },
    "setup_hold_time": { state: 'not_asked' },
    "bus_hold": { state: 'not_asked' },
    "i2c_bus_speed_max_khz": { state: 'not_asked' },
    "input_clamp_diodes": { state: 'not_asked' },
    "input_leakage": { state: 'not_asked' },
    "transition_time": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'C6': {
    "configuration": { state: 'required' },
    "output_voltage": { state: 'required' },
    "adjustability": { state: 'required' },
    "package_case": { state: 'required' },
    "initial_accuracy": { state: 'narrows' },
    "tc": { state: 'narrows' },
    "enable_shutdown_polarity": { state: 'not_asked' },
    "architecture": { state: 'not_asked' },
    "tc_accuracy_grade": { state: 'not_asked' },
    "dropout_voltage": { state: 'not_asked' },
    "input_voltage_range": { state: 'not_asked' },
    "output_noise": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "quiescent_current": { state: 'not_asked' },
    "output_current": { state: 'not_asked' },
    "long_term_stability": { state: 'not_asked' },
    "nr_pin": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
    "packaging": { state: 'not_asked' },
  },
  'C7': {
    "protocol": { state: 'required' },
    "operating_mode": { state: 'required' },
    "data_rate": { state: 'required' },
    "supply_voltage": { state: 'required' },
    "package_case": { state: 'required' },
    "isolation_type": { state: 'narrows' },
    "bus_fault_protection": { state: 'narrows' },
    "de_polarity": { state: 'not_asked' },
    "can_variant": { state: 'not_asked' },
    "txd_dominant_timeout": { state: 'not_asked' },
    "isolation_working_voltage": { state: 'not_asked' },
    "esd_bus_pins": { state: 'not_asked' },
    "receiver_threshold_cm": { state: 'not_asked' },
    "operating_temp": { state: 'not_asked' },
    "failsafe_receiver": { state: 'not_asked' },
    "vod_differential": { state: 'not_asked' },
    "propagation_delay": { state: 'not_asked' },
    "common_mode_range": { state: 'not_asked' },
    "slew_rate_class": { state: 'not_asked' },
    "unit_loads": { state: 'not_asked' },
    "standby_current": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
  },
  'C8': {
    "device_category": { state: 'required' },
    "output_frequency_hz": { state: 'required' },
    "output_signal_type": { state: 'required' },
    "supply_voltage_range": { state: 'required' },
    "package_case": { state: 'required' },
    "initial_tolerance_ppm": { state: 'narrows' },
    "temp_stability_ppm": { state: 'narrows' },
    "oe_polarity": { state: 'not_asked' },
    "vcxo_pull_range_ppm": { state: 'not_asked' },
    "timer_variant": { state: 'not_asked' },
    "output_voh_vol": { state: 'not_asked' },
    "phase_jitter_ps_rms": { state: 'not_asked' },
    "operating_temp_range": { state: 'not_asked' },
    "output_drive_cl_pf": { state: 'not_asked' },
    "icc_active_ma": { state: 'not_asked' },
    "aging_ppm_per_year": { state: 'not_asked' },
    "duty_cycle_pct": { state: 'not_asked' },
    "startup_time_ms": { state: 'not_asked' },
    "icc_standby_ua": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
    "crystal_load_cap_pf": { state: 'not_asked' },
    "packaging_format": { state: 'not_asked' },
  },
  'C9': {
    "architecture": { state: 'required' },
    "resolution_bits": { state: 'required' },
    "interface_type": { state: 'required' },
    "input_configuration": { state: 'required' },
    "channel_count": { state: 'required' },
    "package_case": { state: 'required' },
    "sample_rate_sps": { state: 'narrows' },
    "enob": { state: 'narrows' },
    "simultaneous_sampling": { state: 'narrows' },
    "inl_lsb": { state: 'not_asked' },
    "reference_type": { state: 'not_asked' },
    "input_voltage_range": { state: 'not_asked' },
    "supply_voltage_range": { state: 'not_asked' },
    "operating_temp_range": { state: 'not_asked' },
    "dnl_lsb": { state: 'not_asked' },
    "thd_db": { state: 'not_asked' },
    "conversion_latency_cycles": { state: 'not_asked' },
    "reference_voltage": { state: 'not_asked' },
    "power_consumption_mw": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
  },
  'C10': {
    "output_type": { state: 'required' },
    "resolution_bits": { state: 'required' },
    "interface_type": { state: 'required' },
    "output_buffered": { state: 'required' },
    "package_case": { state: 'required' },
    "update_rate_sps": { state: 'narrows' },
    "power_on_reset_state": { state: 'narrows' },
    "output_voltage_range": { state: 'narrows' },
    "architecture": { state: 'not_asked' },
    "channel_count": { state: 'not_asked' },
    "inl_lsb": { state: 'not_asked' },
    "dnl_lsb": { state: 'not_asked' },
    "glitch_energy_nVs": { state: 'not_asked' },
    "settling_time_us": { state: 'not_asked' },
    "reference_type": { state: 'not_asked' },
    "supply_voltage_range": { state: 'not_asked' },
    "operating_temp_range": { state: 'not_asked' },
    "output_noise_density_nvhz": { state: 'not_asked' },
    "output_current_source_ma": { state: 'not_asked' },
    "reference_voltage": { state: 'not_asked' },
    "power_consumption_mw": { state: 'not_asked' },
    "aec_q100": { state: 'not_asked' },
  },
  'D1': {
    "nominal_frequency_hz": { state: 'required' },
    "load_capacitance_pf": { state: 'required' },
    "package_type": { state: 'required' },
    "cut_type": { state: 'required' },
    "overtone_order": { state: 'required' },
    "equivalent_series_resistance_ohm": { state: 'narrows' },
    "frequency_tolerance_ppm": { state: 'narrows' },
    "frequency_stability_ppm": { state: 'not_asked' },
    "mounting_type": { state: 'not_asked' },
    "drive_level_uw": { state: 'not_asked' },
    "operating_temp_range": { state: 'not_asked' },
    "package_pins": { state: 'not_asked' },
    "shunt_capacitance_pf": { state: 'not_asked' },
    "aging_ppm_per_year": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
    "frequency_vs_temp_curve": { state: 'not_asked' },
    "storage_temp_range": { state: 'not_asked' },
    "qualification_level": { state: 'not_asked' },
  },
  'D2': {
    "current_rating_a": { state: 'required' },
    "voltage_rating_v": { state: 'required' },
    "breaking_capacity_a": { state: 'required' },
    "speed_class": { state: 'required' },
    "package_format": { state: 'required' },
    "voltage_type": { state: 'narrows' },
    "i2t_rating_a2s": { state: 'narrows' },
    "mounting_type": { state: 'not_asked' },
    "safety_certification": { state: 'not_asked' },
    "melting_i2t_a2s": { state: 'not_asked' },
    "body_material": { state: 'not_asked' },
    "operating_temp_range": { state: 'not_asked' },
    "derating_factor": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
  },
  'E1': {
    "output_transistor_type": { state: 'required' },
    "isolation_voltage_vrms": { state: 'required' },
    "channel_count": { state: 'required' },
    "package_type": { state: 'required' },
    "ctr_min_pct": { state: 'narrows' },
    "bandwidth_khz": { state: 'narrows' },
    "working_voltage_vrms": { state: 'not_asked' },
    "creepage_distance_mm": { state: 'not_asked' },
    "vce_sat_v": { state: 'not_asked' },
    "clearance_distance_mm": { state: 'not_asked' },
    "peak_isolation_voltage_v": { state: 'not_asked' },
    "safety_certification": { state: 'not_asked' },
    "ctr_max_pct": { state: 'not_asked' },
    "if_rated_ma": { state: 'not_asked' },
    "input_forward_voltage_vf": { state: 'not_asked' },
    "propagation_delay_us": { state: 'not_asked' },
    "supply_voltage_vcc": { state: 'not_asked' },
    "operating_temp_range": { state: 'not_asked' },
    "ctr_class": { state: 'not_asked' },
    "ctr_degradation_pct": { state: 'not_asked' },
    "pollution_degree": { state: 'not_asked' },
    "output_leakage_iceo_ua": { state: 'not_asked' },
    "aec_q101": { state: 'not_asked' },
  },
  'F1': {
    "coil_voltage_vdc": { state: 'required' },
    "contact_form": { state: 'required' },
    "mounting_type": { state: 'required' },
    "contact_count": { state: 'required' },
    "contact_voltage_rating_v": { state: 'required' },
    "contact_current_rating_a": { state: 'required' },
    "package_footprint": { state: 'narrows' },
    "coil_resistance_ohm": { state: 'narrows' },
    "contact_voltage_type": { state: 'not_asked' },
    "contact_material": { state: 'not_asked' },
    "must_operate_voltage_v": { state: 'not_asked' },
    "operating_temp_range": { state: 'not_asked' },
    "max_switching_power_va": { state: 'not_asked' },
    "coil_power_mw": { state: 'not_asked' },
    "operate_time_ms": { state: 'not_asked' },
    "release_time_ms": { state: 'not_asked' },
    "electrical_life_ops": { state: 'not_asked' },
    "coil_suppress_diode": { state: 'not_asked' },
    "must_release_voltage_v": { state: 'not_asked' },
    "mechanical_life_ops": { state: 'not_asked' },
    "contact_bounce_ms": { state: 'not_asked' },
    "sealing_type": { state: 'not_asked' },
    "aec_q200": { state: 'not_asked' },
  },
  'F2': {
    "output_switch_type": { state: 'required' },
    "firing_mode": { state: 'required' },
    "mounting_type": { state: 'required' },
    "load_voltage_max_v": { state: 'required' },
    "load_current_max_a": { state: 'required' },
    "input_voltage_range_v": { state: 'required' },
    "on_state_voltage_drop_v": { state: 'narrows' },
    "isolation_voltage_vrms": { state: 'narrows' },
    "load_voltage_type": { state: 'not_asked' },
    "off_state_leakage_ma": { state: 'not_asked' },
    "input_current_ma": { state: 'not_asked' },
    "turn_on_time_ms": { state: 'not_asked' },
    "turn_off_time_ms": { state: 'not_asked' },
    "safety_certification": { state: 'not_asked' },
    "operating_temp_range": { state: 'not_asked' },
    "package_footprint": { state: 'not_asked' },
    "load_current_min_a": { state: 'not_asked' },
    "dv_dt_rating_v_us": { state: 'not_asked' },
    "di_dt_rating_a_us": { state: 'not_asked' },
    "thermal_resistance_jc": { state: 'not_asked' },
    "built_in_snubber": { state: 'not_asked' },
    "input_impedance_ohm": { state: 'not_asked' },
    "built_in_varistor": { state: 'not_asked' },
  },
};

/**
 * The ask lists, in ASK ORDER (which is the row order in the source document).
 *   tier2 = Required for Search — always asked, before any search runs.
 *   tier3 = Narrows Results     — asked only when the result set is too large to be useful.
 */
export const SELECTION_TIERS: Record<string, { tier2: string[]; tier3: string[] }> = {
  '12': { tier2: ['capacitance', 'package_case', 'voltage_rated', 'dielectric'], tier3: ['tolerance', 'flexible_termination'] },
  '13': { tier2: ['capacitance', 'package_case', 'voltage_rated', 'dielectric'], tier3: ['tolerance', 'temperature_coefficient'] },
  '52': { tier2: ['resistance', 'package_case', 'power_rating'], tier3: ['tolerance', 'tcr'] },
  '53': { tier2: ['resistance', 'mounting_style', 'lead_spacing', 'power_rating'], tier3: ['tolerance', 'composition'] },
  '54': { tier2: ['resistance', 'package_case', 'power_rating', 'kelvin_sensing'], tier3: ['tolerance', 'tcr'] },
  '55': { tier2: ['resistance', 'power_rating', 'mounting_style', 'heatsink_dimensions'], tier3: ['tolerance', 'thermal_resistance'] },
  '58': { tier2: ['capacitance', 'voltage_rated', 'polarization', 'mounting_type', 'diameter', 'lead_spacing'], tier3: ['esr', 'ripple_current', 'lifetime'] },
  '59': { tier2: ['capacitance', 'voltage_rated', 'package_case', 'capacitor_type'], tier3: ['esr', 'failure_mode'] },
  '60': { tier2: ['capacitance', 'voltage_rated', 'polarization', 'mounting_type', 'esr'], tier3: ['ripple_current', 'tolerance'] },
  '61': { tier2: ['capacitance', 'voltage_rated', 'package_case', 'esr'], tier3: ['leakage_current', 'peak_current'] },
  '64': { tier2: ['capacitance', 'package_case', 'lead_spacing', 'voltage_rated_dc', 'safety_rating'], tier3: ['voltage_rated_ac', 'tolerance', 'dielectric_type'] },
  '65': { tier2: ['varistor_voltage', 'max_continuous_voltage', 'package_case'], tier3: ['energy_rating', 'peak_surge_current', 'safety_rating'] },
  '66': { tier2: ['hold_current', 'max_voltage', 'trip_current', 'package_case'], tier3: ['initial_resistance', 'time_to_trip'] },
  '67': { tier2: ['resistance_r25', 'b_value', 'package_case'], tier3: ['r25_tolerance', 'b_value_tolerance'] },
  '68': { tier2: ['resistance_r25', 'curie_temp', 'package_case'], tier3: ['trip_current', 'hold_current'] },
  '69': { tier2: ['cm_impedance', 'package_case', 'rated_current', 'number_of_lines'], tier3: ['dcr', 'application_type'] },
  '70': { tier2: ['impedance_100mhz', 'package_case', 'rated_current'], tier3: ['dcr', 'number_of_lines'] },
  '71': { tier2: ['inductance', 'package_case', 'saturation_current', 'rated_current'], tier3: ['dcr', 'shielding'] },
  '72': { tier2: ['inductance', 'package_case', 'rated_current', 'srf'], tier3: ['q_factor', 'core_material'] },
  'B1': { tier2: ['vrrm', 'io_avg', 'recovery_category', 'configuration', 'package_case'], tier3: ['vf', 'trr'] },
  'B2': { tier2: ['vrrm', 'io_avg', 'configuration', 'package_case', 'semiconductor_material'], tier3: ['vf', 'ir_leakage'] },
  'B3': { tier2: ['vz', 'pd', 'configuration', 'pin_configuration', 'package_case'], tier3: ['vz_tolerance', 'zzt'] },
  'B4': { tier2: ['polarity', 'vrwm', 'vc', 'num_channels', 'configuration', 'package_case'], tier3: ['ppk', 'cj'] },
  'B5': { tier2: ['channel_type', 'vds_max', 'id_max', 'package_case'], tier3: ['rds_on', 'vgs_th'] },
  'B6': { tier2: ['polarity', 'vceo_max', 'ic_max', 'package_case'], tier3: ['hfe', 'vce_sat'] },
  'B7': { tier2: ['vces_max', 'ic_max', 'package_case', 'co_packaged_diode'], tier3: ['vce_sat', 'eoff'] },
  'B8': { tier2: ['device_type', 'vdrm', 'on_state_current', 'package_case'], tier3: ['igt', 'ih'] },
  'B9': { tier2: ['channel_type', 'vp', 'idss', 'package_case'], tier3: ['gfs', 'igss'] },
  'C1': { tier2: ['output_type', 'polarity', 'output_voltage', 'iout_max', 'package_case'], tier3: ['vdropout', 'output_cap_compatibility'] },
  'C2': { tier2: ['topology', 'architecture', 'vin_max', 'vout_range', 'iout_max', 'package_case'], tier3: ['fsw', 'control_mode', 'vref'] },
  'C3': { tier2: ['driver_configuration', 'isolation_type', 'peak_source_current', 'peak_sink_current', 'vdd_range', 'package_case'], tier3: ['propagation_delay', 'dead_time_control'] },
  'C4': { tier2: ['device_type', 'channels', 'input_type', 'supply_voltage', 'package_case'], tier3: ['gain_bandwidth', 'vicm_range', 'input_bias_current'] },
  'C5': { tier2: ['logic_function', 'gate_count', 'supply_voltage', 'package_case'], tier3: ['logic_family', 'vih', 'tpd'] },
  'C6': { tier2: ['configuration', 'output_voltage', 'adjustability', 'package_case'], tier3: ['initial_accuracy', 'tc'] },
  'C7': { tier2: ['protocol', 'operating_mode', 'data_rate', 'supply_voltage', 'package_case'], tier3: ['isolation_type', 'bus_fault_protection'] },
  'C8': { tier2: ['device_category', 'output_frequency_hz', 'output_signal_type', 'supply_voltage_range', 'package_case'], tier3: ['initial_tolerance_ppm', 'temp_stability_ppm'] },
  'C9': { tier2: ['architecture', 'resolution_bits', 'interface_type', 'input_configuration', 'channel_count', 'package_case'], tier3: ['sample_rate_sps', 'enob', 'simultaneous_sampling'] },
  'C10': { tier2: ['output_type', 'resolution_bits', 'interface_type', 'output_buffered', 'package_case'], tier3: ['update_rate_sps', 'power_on_reset_state', 'output_voltage_range'] },
  'D1': { tier2: ['nominal_frequency_hz', 'load_capacitance_pf', 'package_type', 'cut_type', 'overtone_order'], tier3: ['equivalent_series_resistance_ohm', 'frequency_tolerance_ppm'] },
  'D2': { tier2: ['current_rating_a', 'voltage_rating_v', 'breaking_capacity_a', 'speed_class', 'package_format'], tier3: ['voltage_type', 'i2t_rating_a2s'] },
  'E1': { tier2: ['output_transistor_type', 'isolation_voltage_vrms', 'channel_count', 'package_type'], tier3: ['ctr_min_pct', 'bandwidth_khz'] },
  'F1': { tier2: ['coil_voltage_vdc', 'contact_form', 'mounting_type', 'contact_count', 'contact_voltage_rating_v', 'contact_current_rating_a'], tier3: ['package_footprint', 'coil_resistance_ohm'] },
  'F2': { tier2: ['output_switch_type', 'firing_mode', 'mounting_type', 'load_voltage_max_v', 'load_current_max_a', 'input_voltage_range_v'], tier3: ['on_state_voltage_drop_v', 'isolation_voltage_vrms'] },
};
