// GENERATED FILE — DO NOT EDIT.
// Source of truth: docs/min_attr_sets.md
// Regenerate:      npm run selection:audit
//
// Hand-editing this file re-creates the bug it exists to prevent: a code copy of the
// selection questions that is allowed to drift from the document describing them.

import type { SelectionState } from './selectionDoc';

export interface GeneratedSelectionEntry {
  state: SelectionState;
  reason?: string;
}

/** familyId → attributeId → state. Every scored rule in every family appears here. */
export const SELECTION_STATES: Record<string, Record<string, GeneratedSelectionEntry>> = {
  '12': {
    "capacitance": { state: 'required' },
    "package_case": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "dielectric": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "flexible_termination": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "dc_bias_derating": { state: 'narrows' },
    "operating_temp": { state: 'not_asked', reason: "Encoded by dielectric class (e.g., X7R = -55 to +125C)" },
    "height": { state: 'not_asked', reason: "Tracks EIA case size" },
    "esr": { state: 'not_asked', reason: "Class ceramics are selected by dielectric class, not ESR" },
    "esl": { state: 'not_asked', reason: "Not user-answerable; tracks case size" },
    "msl": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '13': {
    "capacitance": { state: 'required' },
    "package_case": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "dielectric": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "temperature_coefficient": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "esr": { state: 'not_asked', reason: "Not a mica selection criterion users state" },
    "esl": { state: 'not_asked', reason: "Not user-answerable" },
    "msl": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '52': {
    "resistance": { state: 'required' },
    "package_case": { state: 'required' },
    "power_rating": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "tcr": { state: 'narrows' },
    "voltage_rated": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "anti_sulfur": { state: 'narrows' },
    "composition": { state: 'narrows' },
    "operating_temp": { state: 'not_asked', reason: "Near-uniform (-55 to +155C) across chip resistors" },
    "height": { state: 'not_asked', reason: "Tracks case size" },
    "msl": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '53': {
    "resistance": { state: 'required' },
    "mounting_style": { state: 'required' },
    "lead_spacing": { state: 'required' },
    "power_rating": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "composition": { state: 'narrows' },
    "voltage_rated": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "tcr": { state: 'narrows' },
    "body_dimensions": { state: 'narrows' },
    "package_case": { state: 'not_asked', reason: "Axial THT parts have no standard case code; fit is captured by mounting_style + lead_spacing + body_dimensions" },
    "operating_temp": { state: 'not_asked', reason: "Near-uniform across THT resistors" },
    "anti_sulfur": { state: 'not_asked', reason: "Sulfur failure mode is specific to SMD thick-film terminations" },
    "height": { state: 'not_asked', reason: "Captured by body_dimensions" },
    "msl": { state: 'not_asked', reason: "MSL applies to reflow-mounted SMD parts" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '54': {
    "resistance": { state: 'required' },
    "package_case": { state: 'required' },
    "power_rating": { state: 'required' },
    "kelvin_sensing": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "tcr": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "anti_sulfur": { state: 'narrows' },
    "power_rating_pulse": { state: 'narrows' },
    "composition": { state: 'narrows' },
    "parasitic_inductance": { state: 'narrows' },
    "voltage_rated": { state: 'not_asked', reason: "Milliohm-class parts; voltage rating never binds" },
    "operating_temp": { state: 'not_asked', reason: "Near-uniform across current-sense resistors" },
    "height": { state: 'not_asked', reason: "Tracks case size" },
    "msl": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '55': {
    "resistance": { state: 'required' },
    "power_rating": { state: 'required' },
    "mounting_style": { state: 'required' },
    "heatsink_dimensions": { state: 'required' },
    "tolerance": { state: 'narrows' },
    "thermal_resistance": { state: 'narrows' },
    "package_case": { state: 'narrows' },
    "voltage_rated": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "tcr": { state: 'narrows' },
    "composition": { state: 'narrows' },
    "operating_temp": { state: 'not_asked', reason: "Near-uniform for chassis-mount parts" },
    "anti_sulfur": { state: 'not_asked', reason: "Wirewound/chassis construction is not the sulfur failure mode" },
    "height": { state: 'not_asked', reason: "Captured by heatsink_dimensions/package" },
    "msl": { state: 'not_asked', reason: "Chassis-mount; MSL not applicable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '58': {
    "capacitance": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "polarization": { state: 'required' },
    "mounting_type": { state: 'required' },
    "diameter": { state: 'required' },
    "lead_spacing": { state: 'required' },
    "esr": { state: 'narrows' },
    "ripple_current": { state: 'narrows' },
    "lifetime": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "height": { state: 'narrows' },
    "tolerance": { state: 'not_asked', reason: "+/-20% is the de-facto standard for electrolytics; rarely differentiating" },
    "impedance": { state: 'not_asked', reason: "ESR is the asked proxy" },
    "leakage_current": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "capacitor_type": { state: 'not_asked', reason: "Manufacturer series is not a cross-vendor attribute" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '59': {
    "capacitance": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "package_case": { state: 'required' },
    "capacitor_type": { state: 'required' },
    "esr": { state: 'narrows' },
    "failure_mode": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "ripple_current": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "height": { state: 'narrows' },
    "tolerance": { state: 'not_asked', reason: "+/-10/20% standard; rarely differentiating" },
    "surge_voltage": { state: 'not_asked', reason: "Handled by voltage-derating guidance, not a question" },
    "dc_bias_derating": { state: 'not_asked', reason: "Bias derating is a class-II ceramic phenomenon; minimal for tantalum" },
    "leakage_current": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "dissipation_factor": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "msl": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '60': {
    "capacitance": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "polarization": { state: 'required' },
    "mounting_type": { state: 'required' },
    "esr": { state: 'required' },
    "ripple_current": { state: 'narrows' },
    "tolerance": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "lead_spacing": { state: 'narrows', reason: "THT polymer only; irrelevant when mounting_type = SMD" },
    "operating_temp": { state: 'narrows' },
    "diameter": { state: 'narrows' },
    "height": { state: 'narrows' },
    "impedance": { state: 'not_asked', reason: "ESR is the asked proxy" },
    "leakage_current": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "polymer_type": { state: 'not_asked', reason: "Manufacturer construction detail" },
    "capacitor_type": { state: 'not_asked', reason: "Manufacturer series is not a cross-vendor attribute" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '61': {
    "capacitance": { state: 'required' },
    "voltage_rated": { state: 'required' },
    "package_case": { state: 'required' },
    "esr": { state: 'required' },
    "leakage_current": { state: 'narrows' },
    "peak_current": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "technology": { state: 'narrows' },
    "cycle_life": { state: 'narrows' },
    "lifetime": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "diameter": { state: 'narrows' },
    "self_discharge": { state: 'not_asked', reason: "Leakage current is the asked proxy" },
    "height": { state: 'not_asked', reason: "Diameter is the binding dimension for radial cans" },
    "cap_aging": { state: 'not_asked', reason: "Not user-answerable" },
    "esr_aging": { state: 'not_asked', reason: "Not user-answerable" },
    "tolerance": { state: 'not_asked', reason: "+/-20% standard; rarely differentiating" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '64': {
    "capacitance": { state: 'required' },
    "package_case": { state: 'required' },
    "lead_spacing": { state: 'required' },
    "voltage_rated_dc": { state: 'required' },
    "safety_rating": { state: 'required' },
    "voltage_rated_ac": { state: 'narrows' },
    "tolerance": { state: 'narrows' },
    "dielectric_type": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "dv_dt": { state: 'narrows' },
    "height": { state: 'narrows' },
    "self_healing": { state: 'not_asked', reason: "Metallized construction implies self-healing; film/foil is niche" },
    "flammability": { state: 'not_asked', reason: "safety_rating gates mains use; UL94 rarely differentiates further" },
    "ripple_current": { state: 'not_asked', reason: "Relevant only to DC-link/snubber use; application review" },
    "dissipation_factor": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "esr": { state: 'not_asked', reason: "Not a film-cap selection criterion users state" },
    "body_length": { state: 'not_asked', reason: "Lead spacing + case capture fit" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '65': {
    "varistor_voltage": { state: 'required' },
    "max_continuous_voltage": { state: 'required' },
    "package_case": { state: 'required' },
    "energy_rating": { state: 'narrows' },
    "peak_surge_current": { state: 'narrows' },
    "safety_rating": { state: 'narrows' },
    "thermal_disconnect": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "lead_spacing": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "clamping_voltage": { state: 'not_asked', reason: "Tracks varistor_voltage; energy and surge current are the asked differentiators" },
    "disc_diameter": { state: 'not_asked', reason: "Disc size is encoded in package_case" },
    "surge_pulse_lifetime": { state: 'not_asked', reason: "Not user-answerable" },
    "response_time": { state: 'not_asked', reason: "Effectively uniform for MOVs" },
    "leakage_current": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '66': {
    "hold_current": { state: 'required' },
    "max_voltage": { state: 'required' },
    "trip_current": { state: 'required' },
    "package_case": { state: 'required' },
    "initial_resistance": { state: 'narrows' },
    "time_to_trip": { state: 'narrows' },
    "max_fault_current": { state: 'narrows' },
    "safety_rating": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "endurance_cycles": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "post_trip_resistance": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "power_dissipation": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '67': {
    "resistance_r25": { state: 'required' },
    "b_value": { state: 'required' },
    "package_case": { state: 'required' },
    "r25_tolerance": { state: 'narrows' },
    "b_value_tolerance": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "application_category": { state: 'narrows' },
    "rt_curve": { state: 'not_asked', reason: "Vendor-table-specific; R25 + B-value capture it for substitution" },
    "interchangeability": { state: 'not_asked', reason: "Sensing-grade niche; tolerance questions cover accuracy" },
    "max_power": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "thermal_time_constant": { state: 'not_asked', reason: "Not user-answerable" },
    "dissipation_constant": { state: 'not_asked', reason: "Not user-answerable (thermal-resistance-like)" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '68': {
    "resistance_r25": { state: 'required' },
    "curie_temp": { state: 'required' },
    "package_case": { state: 'required' },
    "trip_current": { state: 'narrows' },
    "hold_current": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "max_voltage": { state: 'narrows' },
    "max_current": { state: 'narrows' },
    "rt_curve": { state: 'not_asked', reason: "Vendor-table-specific; R25 + Curie temp capture it for substitution" },
    "operating_temp": { state: 'not_asked', reason: "Curie temperature is the thermal question for PTCs" },
    "interchangeability": { state: 'not_asked', reason: "Sensing-grade niche" },
    "r25_tolerance": { state: 'not_asked', reason: "Protection PTCs don't require sensing-grade tolerance" },
    "max_power": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '69': {
    "cm_impedance": { state: 'required' },
    "package_case": { state: 'required' },
    "rated_current": { state: 'required' },
    "number_of_lines": { state: 'required' },
    "dcr": { state: 'narrows' },
    "application_type": { state: 'narrows' },
    "cm_inductance": { state: 'narrows', reason: "Mains chokes are quoted in mH, signal chokes in ohms; accept either" },
    "aec_q200": { state: 'narrows' },
    "voltage_rated": { state: 'narrows' },
    "safety_rating": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "impedance_curve": { state: 'not_asked', reason: "Curve, not a scalar; not answerable" },
    "interface_compliance": { state: 'not_asked', reason: "Overlaps application_type" },
    "dm_leakage": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "insulation_voltage": { state: 'not_asked', reason: "safety_rating covers" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '70': {
    "impedance_100mhz": { state: 'required' },
    "package_case": { state: 'required' },
    "rated_current": { state: 'required' },
    "dcr": { state: 'narrows' },
    "number_of_lines": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "impedance_curve": { state: 'not_asked', reason: "Curve, not a scalar; not answerable" },
    "signal_integrity": { state: 'not_asked', reason: "S-parameters are not answerable" },
    "operating_temp": { state: 'not_asked', reason: "Near-uniform for ferrite beads" },
    "tolerance": { state: 'not_asked', reason: "+/-25% impedance is standard" },
    "height": { state: 'not_asked', reason: "Tracks case size" },
    "voltage_rated": { state: 'not_asked', reason: "Beads are current-rated; voltage rarely specified" },
    "resistance_type": { state: 'not_asked', reason: "Ambiguous canonical; overlaps dcr -- schema cleanup candidate" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '71': {
    "inductance": { state: 'required' },
    "package_case": { state: 'required' },
    "saturation_current": { state: 'required' },
    "rated_current": { state: 'required' },
    "dcr": { state: 'narrows' },
    "shielding": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "tolerance": { state: 'narrows' },
    "height": { state: 'narrows' },
    "inductance_vs_dc_bias": { state: 'not_asked', reason: "Curve; Isat is the asked proxy" },
    "core_material": { state: 'not_asked', reason: "Captured indirectly by Isat / soft-saturation behavior" },
    "srf": { state: 'not_asked', reason: "SMPS selection is by Isat/Irms; SRF is secondary" },
    "acr": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "construction_type": { state: 'not_asked', reason: "Manufacturer construction detail" },
    "msl": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  '72': {
    "inductance": { state: 'required' },
    "package_case": { state: 'required' },
    "rated_current": { state: 'required' },
    "srf": { state: 'required' },
    "q_factor": { state: 'narrows' },
    "core_material": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "dcr": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "inductance_tolerance": { state: 'narrows' },
    "shielding": { state: 'not_asked', reason: "RF/signal inductors are predominantly unshielded; core_material captures construction" },
    "inductance_vs_dc_bias": { state: 'not_asked', reason: "Curve; not answerable" },
    "tolerance": { state: 'not_asked', reason: "Duplicate of inductance_tolerance -- schema cleanup candidate" },
    "saturation_current": { state: 'not_asked', reason: "RF/signal inductors run far below saturation; not a selection criterion" },
    "height": { state: 'not_asked', reason: "Tracks case size" },
    "acr": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "construction_type": { state: 'not_asked', reason: "Manufacturer construction detail" },
    "msl": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B1': {
    "vrrm": { state: 'required' },
    "io_avg": { state: 'required' },
    "recovery_category": { state: 'required' },
    "configuration": { state: 'required' },
    "package_case": { state: 'required' },
    "vf": { state: 'narrows' },
    "trr": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "ifsm": { state: 'narrows' },
    "pin_configuration": { state: 'not_asked', reason: "Pin compatibility is verified against the original part's datasheet, not asked" },
    "mounting_style": { state: 'not_asked', reason: "Implied by package_case" },
    "vdc": { state: 'not_asked', reason: "Tracks Vrrm" },
    "qrr": { state: 'not_asked', reason: "trr is the asked proxy" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "operating_temp": { state: 'not_asked', reason: "Tj-rated parts; near-uniform" },
    "recovery_behavior": { state: 'not_asked', reason: "Application review" },
    "rth_jc": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "pd": { state: 'not_asked', reason: "Sized by Io; Pd is derived" },
    "ir_leakage": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "rth_ja": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "cj": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B2': {
    "vrrm": { state: 'required' },
    "io_avg": { state: 'required' },
    "configuration": { state: 'required' },
    "package_case": { state: 'required' },
    "semiconductor_material": { state: 'required' },
    "vf": { state: 'narrows' },
    "ir_leakage": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "ifsm": { state: 'narrows' },
    "schottky_technology": { state: 'not_asked', reason: "Overlaps semiconductor_material -- schema cleanup candidate" },
    "pin_configuration": { state: 'not_asked', reason: "Pin compatibility is verified against the original part's datasheet, not asked" },
    "mounting_style": { state: 'not_asked', reason: "Implied by package_case" },
    "rth_jc": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "operating_temp": { state: 'not_asked', reason: "Tj-rated parts; near-uniform" },
    "cj": { state: 'not_asked', reason: "Matters only in RF/detector use; application review" },
    "rth_ja": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "pd": { state: 'not_asked', reason: "Sized by Io; Pd is derived" },
    "vf_tempco": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "technology_trench_planar": { state: 'not_asked', reason: "Manufacturer construction detail" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B3': {
    "vz": { state: 'required' },
    "pd": { state: 'required' },
    "configuration": { state: 'required' },
    "package_case": { state: 'required' },
    "vz_tolerance": { state: 'narrows' },
    "zzt": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "pin_configuration": { state: 'not_asked', reason: "Two-terminal part; polarity handling is a datasheet-verification step, not a question" },
    "mounting_style": { state: 'not_asked', reason: "Implied by package_case" },
    "izt": { state: 'not_asked', reason: "Test condition, not a requirement users state" },
    "tc": { state: 'not_asked', reason: "Matters only for reference-grade use; the Voltage References family (C6) covers that" },
    "operating_temp": { state: 'not_asked', reason: "Tj-rated parts; near-uniform" },
    "izm": { state: 'not_asked', reason: "Derived from Pd and Vz" },
    "rth_ja": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "ir_leakage": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "zzk": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "cj": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "vf": { state: 'not_asked', reason: "Zeners are used in reverse; Vf is immaterial" },
    "regulation_type": { state: 'not_asked', reason: "Implied by Vz (<5V Zener, >5V avalanche)" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B4': {
    "num_channels": { state: 'required' },
    "configuration": { state: 'required' },
    "polarity": { state: 'required' },
    "vrwm": { state: 'required' },
    "vc": { state: 'required' },
    "package_case": { state: 'required' },
    "ppk": { state: 'narrows' },
    "cj": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "surge_standard": { state: 'narrows' },
    "esd_rating": { state: 'narrows' },
    "pin_configuration": { state: 'not_asked', reason: "Pin compatibility is verified against the original part's datasheet, not asked" },
    "vbr": { state: 'not_asked', reason: "Bracketed by Vrwm and Vc" },
    "mounting_style": { state: 'not_asked', reason: "Implied by package_case" },
    "ipp": { state: 'not_asked', reason: "Ppk is the asked proxy" },
    "operating_temp": { state: 'not_asked', reason: "Tj-rated parts; near-uniform" },
    "response_time": { state: 'not_asked', reason: "Effectively uniform for silicon TVS" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "ir_leakage": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "rth_ja": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "pd": { state: 'not_asked', reason: "Transient part; sized by Ppk, not steady-state Pd" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B5': {
    "channel_type": { state: 'required' },
    "vds_max": { state: 'required' },
    "id_max": { state: 'required' },
    "package_case": { state: 'required' },
    "rds_on": { state: 'narrows' },
    "vgs_th": { state: 'narrows' },
    "technology": { state: 'narrows', reason: "Critical above ~650V but noise for the majority of Si searches; ask only to narrow" },
    "aec_q101": { state: 'narrows' },
    "qg": { state: 'narrows' },
    "pin_configuration": { state: 'not_asked', reason: "Pin compatibility is verified against the original part's datasheet, not asked" },
    "mounting_style": { state: 'not_asked', reason: "Implied by package_case" },
    "vgs_max": { state: 'not_asked', reason: "Logic-level compatibility is asked via Vgs(th)" },
    "body_diode_trr": { state: 'not_asked', reason: "Application review" },
    "id_pulse": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "avalanche_energy": { state: 'not_asked', reason: "Application review" },
    "qgd": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "coss": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "crss": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "rth_jc": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "soa": { state: 'not_asked', reason: "Curve; not answerable" },
    "pd": { state: 'not_asked', reason: "Sized by Id; Pd is derived" },
    "qgs": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "ciss": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "body_diode_vf": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "rth_ja": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B6': {
    "polarity": { state: 'required' },
    "vceo_max": { state: 'required' },
    "ic_max": { state: 'required' },
    "package_case": { state: 'required' },
    "hfe": { state: 'narrows' },
    "vce_sat": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "ft": { state: 'narrows' },
    "tst": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "vces_max": { state: 'not_asked', reason: "Vceo is the number users know and quote; Vces adds little" },
    "toff": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "pd": { state: 'not_asked', reason: "Sized by Ic; Pd is derived" },
    "rth_jc": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "soa": { state: 'not_asked', reason: "Curve; not answerable" },
    "vbe_sat": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "ton": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B7': {
    "vces_max": { state: 'required' },
    "ic_max": { state: 'required' },
    "package_case": { state: 'required' },
    "co_packaged_diode": { state: 'required' },
    "vce_sat": { state: 'narrows' },
    "eoff": { state: 'narrows' },
    "tsc": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "channel_type": { state: 'not_asked', reason: "Effectively all IGBTs are N-channel; a zero-information question" },
    "igbt_technology": { state: 'not_asked', reason: "Users don't select by PT/NPT/FS; Vce(sat)/Eoff capture the tradeoff" },
    "mounting_style": { state: 'not_asked', reason: "Implied by package_case" },
    "vge_max": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "eon": { state: 'not_asked', reason: "Eoff is the asked switching-loss proxy" },
    "ic_pulse": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "qg": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "rth_jc": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "soa": { state: 'not_asked', reason: "Curve; not answerable" },
    "pd": { state: 'not_asked', reason: "Sized by Ic; Pd is derived" },
    "vge_th": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "td_on": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "td_off": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "tf": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "height": { state: 'not_asked', reason: "Tracks package" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B8': {
    "device_type": { state: 'required' },
    "vdrm": { state: 'required' },
    "on_state_current": { state: 'required' },
    "package_case": { state: 'required' },
    "igt": { state: 'narrows' },
    "ih": { state: 'narrows' },
    "gate_sensitivity": { state: 'narrows' },
    "snubberless": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "quadrant_operation": { state: 'not_asked', reason: "Drive-design detail; the sensitive-gate question covers MCU triggering" },
    "itsm": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "dv_dt": { state: 'not_asked', reason: "Application review" },
    "i2t": { state: 'not_asked', reason: "Fuse-coordination detail; application review" },
    "il": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "di_dt": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "vdsm": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "vgt": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "tq": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "rth_jc": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "tgt": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'B9': {
    "channel_type": { state: 'required' },
    "vp": { state: 'required' },
    "idss": { state: 'required' },
    "package_case": { state: 'required' },
    "gfs": { state: 'narrows' },
    "igss": { state: 'narrows' },
    "noise_figure": { state: 'narrows' },
    "vds_max": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "fc_1f_corner": { state: 'not_asked', reason: "Not user-answerable" },
    "vgs_max": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "ft": { state: 'not_asked', reason: "Niche; application review" },
    "ciss": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "crss": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "pd_max": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "matched_pair_review": { state: 'not_asked', reason: "Zero-weight placeholder -- schema cleanup candidate" },
  },
  'C1': {
    "output_type": { state: 'required' },
    "polarity": { state: 'required' },
    "output_voltage": { state: 'required' },
    "iout_max": { state: 'required' },
    "vin_max": { state: 'required', reason: "Input rail is always known and a hard safety constraint" },
    "package_case": { state: 'required' },
    "vdropout": { state: 'narrows' },
    "output_cap_compatibility": { state: 'narrows' },
    "enable_pin": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "vout_accuracy": { state: 'narrows' },
    "psrr": { state: 'narrows' },
    "iq": { state: 'narrows' },
    "vin_min": { state: 'not_asked', reason: "The dropout question covers the low end" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "power_good": { state: 'not_asked', reason: "Pin-level feature; verified at datasheet level" },
    "thermal_shutdown": { state: 'not_asked', reason: "Near-universal in modern LDOs" },
    "rth_ja": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "load_regulation": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "soft_start": { state: 'not_asked', reason: "Feature detail; application review" },
    "line_regulation": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'C2': {
    "topology": { state: 'required' },
    "architecture": { state: 'required' },
    "vin_max": { state: 'required' },
    "vout_range": { state: 'required' },
    "iout_max": { state: 'required' },
    "package_case": { state: 'required' },
    "fsw": { state: 'narrows' },
    "control_mode": { state: 'narrows' },
    "vref": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "vin_min": { state: 'narrows' },
    "output_polarity": { state: 'not_asked', reason: "Captured by topology (Inverting/Flyback imply polarity/isolation)" },
    "compensation_type": { state: 'not_asked', reason: "Design-stage detail; control_mode is the asked proxy" },
    "ton_min": { state: 'not_asked', reason: "Derived constraint from Vin/Vout/fsw" },
    "gate_drive_current": { state: 'not_asked', reason: "Controller-only detail; application review" },
    "enable_uvlo": { state: 'not_asked', reason: "Pin-level detail; verified at datasheet level" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "soft_start": { state: 'not_asked', reason: "Feature detail; application review" },
    "ocp_mode": { state: 'not_asked', reason: "Application review" },
    "thermal_shutdown": { state: 'not_asked', reason: "Near-universal" },
    "rth_ja": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'C3': {
    "driver_configuration": { state: 'required' },
    "isolation_type": { state: 'required' },
    "peak_source_current": { state: 'required' },
    "peak_sink_current": { state: 'required' },
    "vdd_range": { state: 'required' },
    "package_case": { state: 'required' },
    "propagation_delay": { state: 'narrows' },
    "dead_time_control": { state: 'narrows' },
    "output_polarity": { state: 'narrows' },
    "isolation_voltage": { state: 'narrows' },
    "input_logic_threshold": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "dead_time": { state: 'not_asked', reason: "dead_time_control is the asked question" },
    "uvlo": { state: 'not_asked', reason: "Tracks the driven-switch technology; application review" },
    "tj_max": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "rise_fall_time": { state: 'not_asked', reason: "Peak source/sink currents are the asked drive-strength proxy" },
    "shutdown_enable": { state: 'not_asked', reason: "Pin-level detail; verified at datasheet level" },
    "bootstrap_diode": { state: 'not_asked', reason: "Verified at datasheet level" },
    "rth_ja": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "fault_reporting": { state: 'not_asked', reason: "Feature detail; application review" },
    "input_vdd_range": { state: 'not_asked', reason: "Follows input_logic_threshold" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'C4': {
    "device_type": { state: 'required' },
    "channels": { state: 'required' },
    "input_type": { state: 'required' },
    "supply_voltage": { state: 'required' },
    "package_case": { state: 'required' },
    "gain_bandwidth": { state: 'narrows' },
    "vicm_range": { state: 'narrows' },
    "input_bias_current": { state: 'narrows' },
    "output_type": { state: 'narrows', reason: "Critical for comparators (open-drain vs push-pull)" },
    "rail_to_rail_output": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "slew_rate": { state: 'narrows' },
    "input_offset_voltage": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "iq": { state: 'narrows' },
    "rail_to_rail_input": { state: 'not_asked', reason: "Captured by the VICM-range question" },
    "min_stable_gain": { state: 'not_asked', reason: "Decompensated amps are niche; application review" },
    "response_time": { state: 'not_asked', reason: "Comparator-only; speed covered in application review" },
    "input_noise_voltage": { state: 'not_asked', reason: "Precision-niche; application review" },
    "output_current": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "avol": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "cmrr": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "psrr": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'C5': {
    "logic_function": { state: 'required' },
    "gate_count": { state: 'required' },
    "supply_voltage": { state: 'required' },
    "package_case": { state: 'required' },
    "logic_family": { state: 'narrows' },
    "vih": { state: 'narrows' },
    "tpd": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "fmax": { state: 'narrows' },
    "oe_polarity": { state: 'not_asked', reason: "Part-number-level detail; captured by logic_function ('241 vs '244)" },
    "output_type": { state: 'not_asked', reason: "Captured by the logic_function suffix (e.g., '07 is open-drain)" },
    "voh": { state: 'not_asked', reason: "VIH is the asked interface-compatibility check (see Engineering Notes)" },
    "drive_current": { state: 'not_asked', reason: "Fanout detail; application review" },
    "schmitt_trigger": { state: 'not_asked', reason: "Encoded in the function number ('14 vs '04)" },
    "vol": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "vil": { state: 'not_asked', reason: "VIH covers the threshold question" },
    "setup_hold_time": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "bus_hold": { state: 'not_asked', reason: "Family-level detail; application review" },
    "i2c_bus_speed_max_khz": { state: 'not_asked', reason: "Misfiled canonical -- I2C bus speed does not apply to 74-series logic; schema cleanup candidate" },
    "input_clamp_diodes": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "input_leakage": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "transition_time": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'C6': {
    "configuration": { state: 'required' },
    "output_voltage": { state: 'required' },
    "adjustability": { state: 'required' },
    "package_case": { state: 'required' },
    "initial_accuracy": { state: 'narrows' },
    "tc": { state: 'narrows' },
    "dropout_voltage": { state: 'narrows' },
    "input_voltage_range": { state: 'narrows' },
    "output_noise": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "enable_shutdown_polarity": { state: 'not_asked', reason: "Pin-level detail; verified at datasheet level" },
    "architecture": { state: 'not_asked', reason: "Users specify accuracy/TC, not internal architecture" },
    "tc_accuracy_grade": { state: 'not_asked', reason: "Redundant with the initial_accuracy + tc questions" },
    "quiescent_current": { state: 'not_asked', reason: "Near-duplicate of iq canonical -- schema cleanup candidate; application review" },
    "output_current": { state: 'not_asked', reason: "The series/shunt configuration question covers the load class" },
    "long_term_stability": { state: 'not_asked', reason: "Precision-niche; application review" },
    "nr_pin": { state: 'not_asked', reason: "Feature detail; verified at datasheet level" },
    "packaging": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'C7': {
    "protocol": { state: 'required' },
    "operating_mode": { state: 'required' },
    "data_rate": { state: 'required' },
    "supply_voltage": { state: 'required' },
    "package_case": { state: 'required' },
    "isolation_type": { state: 'narrows' },
    "bus_fault_protection": { state: 'narrows' },
    "esd_bus_pins": { state: 'narrows' },
    "operating_temp": { state: 'narrows' },
    "propagation_delay": { state: 'narrows' },
    "unit_loads": { state: 'narrows', reason: "RS-485 node count is user-known" },
    "aec_q100": { state: 'narrows' },
    "de_polarity": { state: 'not_asked', reason: "Pinout detail; verified at datasheet level" },
    "can_variant": { state: 'not_asked', reason: "Captured by protocol + data_rate (e.g., 5 Mbps implies CAN FD)" },
    "txd_dominant_timeout": { state: 'not_asked', reason: "Feature detail; application review" },
    "isolation_working_voltage": { state: 'not_asked', reason: "Follows isolation_type; refined in application review" },
    "receiver_threshold_cm": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "failsafe_receiver": { state: 'not_asked', reason: "Feature detail; application review" },
    "vod_differential": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "common_mode_range": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "slew_rate_class": { state: 'not_asked', reason: "Follows data_rate" },
    "standby_current": { state: 'not_asked', reason: "Application review" },
  },
  'C8': {
    "device_category": { state: 'required' },
    "output_frequency_hz": { state: 'required' },
    "output_signal_type": { state: 'required' },
    "supply_voltage_range": { state: 'required' },
    "package_case": { state: 'required' },
    "initial_tolerance_ppm": { state: 'narrows' },
    "temp_stability_ppm": { state: 'narrows' },
    "vcxo_pull_range_ppm": { state: 'narrows' },
    "timer_variant": { state: 'narrows' },
    "phase_jitter_ps_rms": { state: 'narrows' },
    "operating_temp_range": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "oe_polarity": { state: 'not_asked', reason: "Pinout detail; verified at datasheet level" },
    "output_voh_vol": { state: 'not_asked', reason: "Follows output_signal_type and supply" },
    "output_drive_cl_pf": { state: 'not_asked', reason: "Design-point detail; application review" },
    "icc_active_ma": { state: 'not_asked', reason: "Application review" },
    "aging_ppm_per_year": { state: 'not_asked', reason: "Precision-niche; application review" },
    "duty_cycle_pct": { state: 'not_asked', reason: "Near-uniform for XOs" },
    "startup_time_ms": { state: 'not_asked', reason: "Application review" },
    "icc_standby_ua": { state: 'not_asked', reason: "Application review" },
    "crystal_load_cap_pf": { state: 'not_asked', reason: "Crystal-family (D1) attribute misfiled here -- schema cleanup candidate" },
    "packaging_format": { state: 'not_asked', reason: "Procurement/assembly attribute, not a selection criterion" },
  },
  'C9': {
    "architecture": { state: 'required' },
    "resolution_bits": { state: 'required' },
    "interface_type": { state: 'required' },
    "input_configuration": { state: 'required' },
    "channel_count": { state: 'required' },
    "package_case": { state: 'required' },
    "sample_rate_sps": { state: 'narrows' },
    "enob": { state: 'narrows' },
    "simultaneous_sampling": { state: 'narrows' },
    "reference_type": { state: 'narrows' },
    "input_voltage_range": { state: 'narrows' },
    "supply_voltage_range": { state: 'narrows' },
    "operating_temp_range": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "inl_lsb": { state: 'not_asked', reason: "ENOB is the asked precision proxy" },
    "dnl_lsb": { state: 'not_asked', reason: "ENOB is the asked precision proxy" },
    "thd_db": { state: 'not_asked', reason: "ENOB is the asked precision proxy" },
    "conversion_latency_cycles": { state: 'not_asked', reason: "Architecture implies latency class; application review" },
    "reference_voltage": { state: 'not_asked', reason: "Follows reference_type" },
    "power_consumption_mw": { state: 'not_asked', reason: "Application review" },
  },
  'C10': {
    "output_type": { state: 'required' },
    "resolution_bits": { state: 'required' },
    "channel_count": { state: 'required', reason: "Identity-level: single/dual/quad DACs have different pinouts" },
    "interface_type": { state: 'required' },
    "output_buffered": { state: 'required' },
    "package_case": { state: 'required' },
    "update_rate_sps": { state: 'narrows' },
    "power_on_reset_state": { state: 'narrows' },
    "output_voltage_range": { state: 'narrows' },
    "architecture": { state: 'narrows' },
    "settling_time_us": { state: 'narrows' },
    "reference_type": { state: 'narrows' },
    "supply_voltage_range": { state: 'narrows' },
    "operating_temp_range": { state: 'narrows' },
    "aec_q100": { state: 'narrows' },
    "inl_lsb": { state: 'not_asked', reason: "Resolution + settling cover; application review" },
    "dnl_lsb": { state: 'not_asked', reason: "Resolution + settling cover; application review" },
    "glitch_energy_nVs": { state: 'not_asked', reason: "Application review" },
    "output_noise_density_nvhz": { state: 'not_asked', reason: "Precision-niche; application review" },
    "output_current_source_ma": { state: 'not_asked', reason: "The buffered question covers drive class" },
    "reference_voltage": { state: 'not_asked', reason: "Follows reference_type" },
    "power_consumption_mw": { state: 'not_asked', reason: "Application review" },
  },
  'D1': {
    "nominal_frequency_hz": { state: 'required' },
    "load_capacitance_pf": { state: 'required' },
    "package_type": { state: 'required' },
    "cut_type": { state: 'required' },
    "overtone_order": { state: 'required' },
    "equivalent_series_resistance_ohm": { state: 'narrows' },
    "frequency_tolerance_ppm": { state: 'narrows' },
    "frequency_stability_ppm": { state: 'narrows' },
    "operating_temp_range": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "mounting_type": { state: 'not_asked', reason: "Implied by package_type" },
    "drive_level_uw": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "package_pins": { state: 'not_asked', reason: "Implied by package_type" },
    "shunt_capacitance_pf": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "aging_ppm_per_year": { state: 'not_asked', reason: "Precision-niche; application review" },
    "frequency_vs_temp_curve": { state: 'not_asked', reason: "Curve; not answerable" },
    "storage_temp_range": { state: 'not_asked', reason: "Users cannot state a storage temperature" },
    "qualification_level": { state: 'not_asked', reason: "Generic catch-all; overlaps aec_q200 -- schema cleanup candidate" },
  },
  'D2': {
    "current_rating_a": { state: 'required' },
    "voltage_rating_v": { state: 'required' },
    "breaking_capacity_a": { state: 'required' },
    "speed_class": { state: 'required' },
    "package_format": { state: 'required' },
    "voltage_type": { state: 'narrows' },
    "i2t_rating_a2s": { state: 'narrows' },
    "safety_certification": { state: 'narrows' },
    "operating_temp_range": { state: 'narrows' },
    "aec_q200": { state: 'narrows' },
    "mounting_type": { state: 'not_asked', reason: "Captured by package_format" },
    "melting_i2t_a2s": { state: 'not_asked', reason: "Clearing I2t is the asked value" },
    "body_material": { state: 'not_asked', reason: "Breaking capacity is the functional question; body material is a proxy" },
    "derating_factor": { state: 'not_asked', reason: "Derived design guidance, not a part attribute" },
  },
  'E1': {
    "output_transistor_type": { state: 'required' },
    "isolation_voltage_vrms": { state: 'required' },
    "channel_count": { state: 'required' },
    "package_type": { state: 'required' },
    "ctr_min_pct": { state: 'narrows' },
    "bandwidth_khz": { state: 'narrows' },
    "working_voltage_vrms": { state: 'narrows' },
    "creepage_distance_mm": { state: 'narrows' },
    "safety_certification": { state: 'narrows' },
    "operating_temp_range": { state: 'narrows' },
    "aec_q101": { state: 'narrows' },
    "vce_sat_v": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "clearance_distance_mm": { state: 'not_asked', reason: "Creepage is the binding asked constraint" },
    "peak_isolation_voltage_v": { state: 'not_asked', reason: "isolation_voltage_vrms covers" },
    "ctr_max_pct": { state: 'not_asked', reason: "CTR minimum covers" },
    "if_rated_ma": { state: 'not_asked', reason: "Design-point detail; application review" },
    "input_forward_voltage_vf": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "propagation_delay_us": { state: 'not_asked', reason: "Bandwidth is the asked speed proxy" },
    "supply_voltage_vcc": { state: 'not_asked', reason: "Applies only to IC-output types; application review" },
    "ctr_class": { state: 'not_asked', reason: "Manufacturer binning; ctr_min covers" },
    "ctr_degradation_pct": { state: 'not_asked', reason: "Lifetime-modeling detail; not answerable" },
    "pollution_degree": { state: 'not_asked', reason: "System-level parameter, not a part question" },
    "output_leakage_iceo_ua": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
  },
  'F1': {
    "coil_voltage_vdc": { state: 'required' },
    "contact_form": { state: 'required' },
    "mounting_type": { state: 'required' },
    "contact_count": { state: 'required' },
    "contact_voltage_rating_v": { state: 'required' },
    "contact_current_rating_a": { state: 'required' },
    "package_footprint": { state: 'narrows' },
    "coil_resistance_ohm": { state: 'narrows' },
    "contact_voltage_type": { state: 'narrows', reason: "AC vs DC load radically changes effective contact rating" },
    "operating_temp_range": { state: 'narrows' },
    "electrical_life_ops": { state: 'narrows' },
    "coil_suppress_diode": { state: 'narrows', reason: "Built-in diode changes drive circuit and coil polarity" },
    "aec_q200": { state: 'narrows' },
    "contact_material": { state: 'not_asked', reason: "Load class captured by voltage/current ratings; signal-level relays handled in application review" },
    "must_operate_voltage_v": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "max_switching_power_va": { state: 'not_asked', reason: "Derived from V x I ratings" },
    "coil_power_mw": { state: 'not_asked', reason: "Follows coil voltage/resistance" },
    "operate_time_ms": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "release_time_ms": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "must_release_voltage_v": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "mechanical_life_ops": { state: 'not_asked', reason: "Electrical life is the binding number" },
    "contact_bounce_ms": { state: 'not_asked', reason: "Datasheet-derived; not user-answerable" },
    "sealing_type": { state: 'not_asked', reason: "Assembly-process attribute; application review" },
  },
  'F2': {
    "output_switch_type": { state: 'required' },
    "firing_mode": { state: 'required' },
    "mounting_type": { state: 'required' },
    "load_voltage_max_v": { state: 'required' },
    "load_current_max_a": { state: 'required' },
    "input_voltage_range_v": { state: 'required' },
    "on_state_voltage_drop_v": { state: 'narrows' },
    "isolation_voltage_vrms": { state: 'narrows' },
    "off_state_leakage_ma": { state: 'narrows', reason: "Matters for small AC loads (e.g., LED lamps staying lit)" },
    "safety_certification": { state: 'narrows' },
    "operating_temp_range": { state: 'narrows' },
    "package_footprint": { state: 'narrows' },
    "built_in_snubber": { state: 'narrows' },
    "load_voltage_type": { state: 'not_asked', reason: "Implied by output_switch_type (TRIAC = AC; MOSFET = DC)" },
    "input_current_ma": { state: 'not_asked', reason: "Follows input_voltage_range" },
    "turn_on_time_ms": { state: 'not_asked', reason: "Firing mode captures the switching-behavior class" },
    "turn_off_time_ms": { state: 'not_asked', reason: "Firing mode captures the switching-behavior class" },
    "load_current_min_a": { state: 'not_asked', reason: "Datasheet footnote; the leakage question covers small-load risk" },
    "dv_dt_rating_v_us": { state: 'not_asked', reason: "Application review" },
    "di_dt_rating_a_us": { state: 'not_asked', reason: "Application review" },
    "thermal_resistance_jc": { state: 'not_asked', reason: "Thermal metric; not user-answerable" },
    "input_impedance_ohm": { state: 'not_asked', reason: "Follows input spec" },
    "built_in_varistor": { state: 'not_asked', reason: "The snubber question covers protection add-ons" },
  },
};

/**
 * The ask lists, in ASK ORDER (which is the row order in the source document).
 *   tier2 = Required for Search — always asked, before any search runs.
 *   tier3 = Narrows Results     — asked only when the result set is too large to be useful.
 */
export const SELECTION_TIERS: Record<string, { tier2: string[]; tier3: string[] }> = {
  '12': { tier2: ['capacitance', 'package_case', 'voltage_rated', 'dielectric'], tier3: ['tolerance', 'flexible_termination', 'aec_q200', 'dc_bias_derating'] },
  '13': { tier2: ['capacitance', 'package_case', 'voltage_rated', 'dielectric'], tier3: ['tolerance', 'temperature_coefficient', 'operating_temp', 'aec_q200'] },
  '52': { tier2: ['resistance', 'package_case', 'power_rating'], tier3: ['tolerance', 'tcr', 'voltage_rated', 'aec_q200', 'anti_sulfur', 'composition'] },
  '53': { tier2: ['resistance', 'mounting_style', 'lead_spacing', 'power_rating'], tier3: ['tolerance', 'composition', 'voltage_rated', 'aec_q200', 'tcr', 'body_dimensions'] },
  '54': { tier2: ['resistance', 'package_case', 'power_rating', 'kelvin_sensing'], tier3: ['tolerance', 'tcr', 'aec_q200', 'anti_sulfur', 'power_rating_pulse', 'composition', 'parasitic_inductance'] },
  '55': { tier2: ['resistance', 'power_rating', 'mounting_style', 'heatsink_dimensions'], tier3: ['tolerance', 'thermal_resistance', 'package_case', 'voltage_rated', 'aec_q200', 'tcr', 'composition'] },
  '58': { tier2: ['capacitance', 'voltage_rated', 'polarization', 'mounting_type', 'diameter', 'lead_spacing'], tier3: ['esr', 'ripple_current', 'lifetime', 'aec_q200', 'operating_temp', 'height'] },
  '59': { tier2: ['capacitance', 'voltage_rated', 'package_case', 'capacitor_type'], tier3: ['esr', 'failure_mode', 'aec_q200', 'ripple_current', 'operating_temp', 'height'] },
  '60': { tier2: ['capacitance', 'voltage_rated', 'polarization', 'mounting_type', 'esr'], tier3: ['ripple_current', 'tolerance', 'aec_q200', 'lead_spacing', 'operating_temp', 'diameter', 'height'] },
  '61': { tier2: ['capacitance', 'voltage_rated', 'package_case', 'esr'], tier3: ['leakage_current', 'peak_current', 'aec_q200', 'technology', 'cycle_life', 'lifetime', 'operating_temp', 'diameter'] },
  '64': { tier2: ['capacitance', 'package_case', 'lead_spacing', 'voltage_rated_dc', 'safety_rating'], tier3: ['voltage_rated_ac', 'tolerance', 'dielectric_type', 'aec_q200', 'operating_temp', 'dv_dt', 'height'] },
  '65': { tier2: ['varistor_voltage', 'max_continuous_voltage', 'package_case'], tier3: ['energy_rating', 'peak_surge_current', 'safety_rating', 'thermal_disconnect', 'aec_q200', 'lead_spacing', 'operating_temp'] },
  '66': { tier2: ['hold_current', 'max_voltage', 'trip_current', 'package_case'], tier3: ['initial_resistance', 'time_to_trip', 'max_fault_current', 'safety_rating', 'aec_q200', 'operating_temp'] },
  '67': { tier2: ['resistance_r25', 'b_value', 'package_case'], tier3: ['r25_tolerance', 'b_value_tolerance', 'aec_q200', 'operating_temp', 'application_category'] },
  '68': { tier2: ['resistance_r25', 'curie_temp', 'package_case'], tier3: ['trip_current', 'hold_current', 'aec_q200', 'max_voltage', 'max_current'] },
  '69': { tier2: ['cm_impedance', 'package_case', 'rated_current', 'number_of_lines'], tier3: ['dcr', 'application_type', 'cm_inductance', 'aec_q200', 'voltage_rated', 'safety_rating', 'operating_temp'] },
  '70': { tier2: ['impedance_100mhz', 'package_case', 'rated_current'], tier3: ['dcr', 'number_of_lines', 'aec_q200'] },
  '71': { tier2: ['inductance', 'package_case', 'saturation_current', 'rated_current'], tier3: ['dcr', 'shielding', 'aec_q200', 'operating_temp', 'tolerance', 'height'] },
  '72': { tier2: ['inductance', 'package_case', 'rated_current', 'srf'], tier3: ['q_factor', 'core_material', 'aec_q200', 'dcr', 'operating_temp', 'inductance_tolerance'] },
  'B1': { tier2: ['vrrm', 'io_avg', 'recovery_category', 'configuration', 'package_case'], tier3: ['vf', 'trr', 'aec_q101', 'ifsm'] },
  'B2': { tier2: ['vrrm', 'io_avg', 'configuration', 'package_case', 'semiconductor_material'], tier3: ['vf', 'ir_leakage', 'aec_q101', 'ifsm'] },
  'B3': { tier2: ['vz', 'pd', 'configuration', 'package_case'], tier3: ['vz_tolerance', 'zzt', 'aec_q101'] },
  'B4': { tier2: ['num_channels', 'configuration', 'polarity', 'vrwm', 'vc', 'package_case'], tier3: ['ppk', 'cj', 'aec_q101', 'surge_standard', 'esd_rating'] },
  'B5': { tier2: ['channel_type', 'vds_max', 'id_max', 'package_case'], tier3: ['rds_on', 'vgs_th', 'technology', 'aec_q101', 'qg'] },
  'B6': { tier2: ['polarity', 'vceo_max', 'ic_max', 'package_case'], tier3: ['hfe', 'vce_sat', 'aec_q101', 'ft'] },
  'B7': { tier2: ['vces_max', 'ic_max', 'package_case', 'co_packaged_diode'], tier3: ['vce_sat', 'eoff', 'tsc', 'aec_q101'] },
  'B8': { tier2: ['device_type', 'vdrm', 'on_state_current', 'package_case'], tier3: ['igt', 'ih', 'gate_sensitivity', 'snubberless', 'aec_q101'] },
  'B9': { tier2: ['channel_type', 'vp', 'idss', 'package_case'], tier3: ['gfs', 'igss', 'noise_figure', 'vds_max', 'aec_q101'] },
  'C1': { tier2: ['output_type', 'polarity', 'output_voltage', 'iout_max', 'vin_max', 'package_case'], tier3: ['vdropout', 'output_cap_compatibility', 'enable_pin', 'aec_q100', 'vout_accuracy', 'psrr', 'iq'] },
  'C2': { tier2: ['topology', 'architecture', 'vin_max', 'vout_range', 'iout_max', 'package_case'], tier3: ['fsw', 'control_mode', 'vref', 'aec_q100', 'vin_min'] },
  'C3': { tier2: ['driver_configuration', 'isolation_type', 'peak_source_current', 'peak_sink_current', 'vdd_range', 'package_case'], tier3: ['propagation_delay', 'dead_time_control', 'output_polarity', 'isolation_voltage', 'input_logic_threshold', 'aec_q100'] },
  'C4': { tier2: ['device_type', 'channels', 'input_type', 'supply_voltage', 'package_case'], tier3: ['gain_bandwidth', 'vicm_range', 'input_bias_current', 'output_type', 'rail_to_rail_output', 'aec_q100', 'slew_rate', 'input_offset_voltage', 'operating_temp', 'iq'] },
  'C5': { tier2: ['logic_function', 'gate_count', 'supply_voltage', 'package_case'], tier3: ['logic_family', 'vih', 'tpd', 'aec_q100', 'operating_temp', 'fmax'] },
  'C6': { tier2: ['configuration', 'output_voltage', 'adjustability', 'package_case'], tier3: ['initial_accuracy', 'tc', 'dropout_voltage', 'input_voltage_range', 'output_noise', 'operating_temp', 'aec_q100'] },
  'C7': { tier2: ['protocol', 'operating_mode', 'data_rate', 'supply_voltage', 'package_case'], tier3: ['isolation_type', 'bus_fault_protection', 'esd_bus_pins', 'operating_temp', 'propagation_delay', 'unit_loads', 'aec_q100'] },
  'C8': { tier2: ['device_category', 'output_frequency_hz', 'output_signal_type', 'supply_voltage_range', 'package_case'], tier3: ['initial_tolerance_ppm', 'temp_stability_ppm', 'vcxo_pull_range_ppm', 'timer_variant', 'phase_jitter_ps_rms', 'operating_temp_range', 'aec_q100'] },
  'C9': { tier2: ['architecture', 'resolution_bits', 'interface_type', 'input_configuration', 'channel_count', 'package_case'], tier3: ['sample_rate_sps', 'enob', 'simultaneous_sampling', 'reference_type', 'input_voltage_range', 'supply_voltage_range', 'operating_temp_range', 'aec_q100'] },
  'C10': { tier2: ['output_type', 'resolution_bits', 'channel_count', 'interface_type', 'output_buffered', 'package_case'], tier3: ['update_rate_sps', 'power_on_reset_state', 'output_voltage_range', 'architecture', 'settling_time_us', 'reference_type', 'supply_voltage_range', 'operating_temp_range', 'aec_q100'] },
  'D1': { tier2: ['nominal_frequency_hz', 'load_capacitance_pf', 'package_type', 'cut_type', 'overtone_order'], tier3: ['equivalent_series_resistance_ohm', 'frequency_tolerance_ppm', 'frequency_stability_ppm', 'operating_temp_range', 'aec_q200'] },
  'D2': { tier2: ['current_rating_a', 'voltage_rating_v', 'breaking_capacity_a', 'speed_class', 'package_format'], tier3: ['voltage_type', 'i2t_rating_a2s', 'safety_certification', 'operating_temp_range', 'aec_q200'] },
  'E1': { tier2: ['output_transistor_type', 'isolation_voltage_vrms', 'channel_count', 'package_type'], tier3: ['ctr_min_pct', 'bandwidth_khz', 'working_voltage_vrms', 'creepage_distance_mm', 'safety_certification', 'operating_temp_range', 'aec_q101'] },
  'F1': { tier2: ['coil_voltage_vdc', 'contact_form', 'mounting_type', 'contact_count', 'contact_voltage_rating_v', 'contact_current_rating_a'], tier3: ['package_footprint', 'coil_resistance_ohm', 'contact_voltage_type', 'operating_temp_range', 'electrical_life_ops', 'coil_suppress_diode', 'aec_q200'] },
  'F2': { tier2: ['output_switch_type', 'firing_mode', 'mounting_type', 'load_voltage_max_v', 'load_current_max_a', 'input_voltage_range_v'], tier3: ['on_state_voltage_drop_v', 'isolation_voltage_vrms', 'off_state_leakage_ma', 'safety_certification', 'operating_temp_range', 'package_footprint', 'built_in_snubber'] },
};
