import { LogicTable } from '../types';

/**
 * Aluminum Electrolytic Capacitors Logic Table
 * DigiKey Family ID: 58
 *
 * Derived from: docs/aluminum_electrolytic_logic.docx
 * 17 attributes with specific matching rules for cross-reference validation.
 */
export const aluminumElectrolyticLogicTable: LogicTable = {
  familyId: '58',
  familyName: 'Aluminum Electrolytic Capacitors',
  category: 'Passives',
  description: 'Hard logic filters for aluminum electrolytic capacitor replacement part validation',
  rules: [
    {
      attributeId: 'capacitance',
      attributeName: 'Capacitance',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'Capacitance must match exactly. Ensure values are normalized (µF) before comparison.',
      sortOrder: 1,
    },
    {
      attributeId: 'voltage_rated',
      attributeName: 'Voltage Rating',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 9,
      engineeringReason: 'The replacement must handle at least the same voltage. Higher voltage rating is always acceptable but may increase size.',
      sortOrder: 2,
    },
    {
      attributeId: 'polarization',
      attributeName: 'Polarization',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'Polar and non-polar (bipolar) types are not interchangeable. A polar cap in an AC circuit will fail catastrophically.',
      sortOrder: 3,
    },
    {
      attributeId: 'mounting_type',
      attributeName: 'Mounting Type',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'SMD and through-hole types are not interchangeable without PCB redesign. Snap-in vs radial lead also matters.',
      sortOrder: 4,
    },
    {
      attributeId: 'diameter',
      attributeName: 'Diameter',
      logicType: 'fit',
      weight: 6,
      engineeringReason: 'Must fit within the PCB footprint and available board area. Especially important for snap-in types.',
      sortOrder: 5,
    },
    {
      attributeId: 'height',
      attributeName: 'Height',
      logicType: 'fit',
      weight: 6,
      engineeringReason: 'Must fit within available vertical clearance. Electrolytic capacitors are often the tallest component on a board.',
      sortOrder: 6,
    },
    {
      attributeId: 'lead_spacing',
      attributeName: 'Lead Spacing',
      logicType: 'identity',
      weight: 7,
      engineeringReason: 'Lead spacing must match for through-hole types. Different spacing requires different PCB hole patterns.',
      sortOrder: 7,
    },
    {
      attributeId: 'tolerance',
      attributeName: 'Tolerance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'A tighter tolerance is always acceptable. Electrolytics typically have wide tolerances: ±20%(M) is most common.',
      sortOrder: 8,
    },
    {
      attributeId: 'esr',
      attributeName: 'ESR',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 7,
      engineeringReason: 'Lower ESR is critical for power supply output filtering. High ESR causes ripple voltage and heating.',
      sortOrder: 9,
    },
    {
      attributeId: 'ripple_current',
      attributeName: 'Ripple Current',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 8,
      engineeringReason: 'The replacement must handle at least the same ripple current. This is the #1 reliability parameter for electrolytics in power supplies. Insufficient rating causes overheating and premature dryout.',
      sortOrder: 10,
    },
    {
      attributeId: 'impedance',
      attributeName: 'Impedance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Lower impedance is better for filtering. Impedance at 100kHz is the standard comparison point.',
      sortOrder: 11,
    },
    {
      attributeId: 'leakage_current',
      attributeName: 'Leakage Current',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Lower leakage is better. Critical for battery-powered and standby power designs.',
      sortOrder: 12,
    },
    {
      attributeId: 'lifetime',
      attributeName: 'Lifetime / Endurance',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'Longer lifetime is always acceptable. Rated in hours at max temp (e.g., 2000h @ 105°C). The electrolyte dries out over time — this is the primary wear-out mechanism.',
      sortOrder: 13,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temp Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 7,
      engineeringReason: 'The replacement must cover at least the full operating temperature range. Every 10°C above rated temp halves the lifetime.',
      sortOrder: 14,
    },
    {
      attributeId: 'capacitor_type',
      attributeName: 'Capacitor Type / Series',
      logicType: 'identity_upgrade',
      upgradeHierarchy: ['Hybrid', 'Polymer Hybrid', 'Low ESR', 'Standard'],
      weight: 4,
      engineeringReason: 'Hybrid and polymer hybrid electrolytics offer lower ESR and longer life than standard types. Upgrading is generally safe.',
      sortOrder: 15,
    },
    {
      attributeId: 'aec_q200',
      attributeName: 'AEC-Q200 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Required for automotive applications. A non-qualified part cannot replace a qualified one.',
      sortOrder: 16,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'Tape & Reel for SMD, bulk or ammo pack for through-hole. Ensure packaging matches production line requirements.',
      sortOrder: 17,
    },
  ],
};
