import { LogicTable } from '../types';

/**
 * Common Mode Chokes Logic Table
 * DigiKey Family ID: 69
 *
 * Derived from: docs/common_mode_chokes_logic.docx
 * 17 attributes with specific matching rules for cross-reference validation.
 */
export const commonModeChokesLogicTable: LogicTable = {
  familyId: '69',
  familyName: 'Common Mode Chokes / Filters',
  category: 'Passives',
  description: 'Hard logic filters for common mode choke replacement part validation',
  rules: [
    {
      attributeId: 'cm_impedance',
      attributeName: 'Common Mode Impedance',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'The primary specification. Common mode impedance at the rated frequency must match. This determines the noise suppression capability.',
      sortOrder: 1,
    },
    {
      attributeId: 'cm_inductance',
      attributeName: 'Common Mode Inductance',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 8,
      engineeringReason: 'Higher common mode inductance provides better low-frequency noise suppression. The replacement must provide at least the same inductance.',
      sortOrder: 2,
    },
    {
      attributeId: 'impedance_curve',
      attributeName: 'Impedance vs Frequency Curve',
      logicType: 'application_review',
      weight: 8,
      engineeringReason: 'The frequency response shape determines effectiveness across the target range. Two chokes with the same rated impedance can behave very differently. Consult datasheets.',
      sortOrder: 3,
    },
    {
      attributeId: 'number_of_lines',
      attributeName: 'Number of Lines',
      logicType: 'identity',
      weight: 7,
      engineeringReason: 'Number of signal lines (2, 4, etc.) must match. Determines the pin count and circuit configuration.',
      sortOrder: 4,
    },
    {
      attributeId: 'dm_leakage',
      attributeName: 'Differential Mode Leakage Inductance',
      logicType: 'application_review',
      weight: 6,
      engineeringReason: 'DM leakage inductance affects signal integrity. Too much leakage attenuates the desired differential signal. Too little reduces DM noise filtering. Must review for the specific application.',
      sortOrder: 5,
    },
    {
      attributeId: 'package_case',
      attributeName: 'Package / Case',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'The replacement must match the original footprint exactly. Common mode chokes have specific pin configurations.',
      sortOrder: 6,
    },
    {
      attributeId: 'rated_current',
      attributeName: 'Rated Current',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 9,
      engineeringReason: 'The replacement must handle at least the same current. Exceeding rated current causes core saturation and loss of filtering.',
      sortOrder: 7,
    },
    {
      attributeId: 'dcr',
      attributeName: 'DC Resistance (DCR)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 7,
      engineeringReason: 'Lower DCR means less voltage drop and less power loss per line.',
      sortOrder: 8,
    },
    {
      attributeId: 'voltage_rated',
      attributeName: 'Voltage Rating',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'The replacement must handle at least the same working voltage.',
      sortOrder: 9,
    },
    {
      attributeId: 'insulation_voltage',
      attributeName: 'Insulation Voltage',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 6,
      engineeringReason: 'Higher insulation voltage provides better isolation between windings. Critical for safety-rated applications.',
      sortOrder: 10,
    },
    {
      attributeId: 'application_type',
      attributeName: 'Application Type',
      logicType: 'identity',
      weight: 5,
      engineeringReason: 'Signal-line (USB, HDMI) vs power-line chokes have very different characteristics. They are not interchangeable.',
      sortOrder: 11,
    },
    {
      attributeId: 'interface_compliance',
      attributeName: 'Interface Compliance',
      logicType: 'identity_flag',
      weight: 7,
      engineeringReason: 'If original is designed for specific interface (USB 3.0, HDMI 2.1, Ethernet), replacement must also comply. Interface-specific chokes are optimized for that standard\'s frequency range.',
      sortOrder: 12,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temp Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 6,
      engineeringReason: 'The replacement must cover at least the full operating temperature range of the original.',
      sortOrder: 13,
    },
    {
      attributeId: 'height',
      attributeName: 'Height (Seated Max)',
      logicType: 'fit',
      weight: 5,
      engineeringReason: 'Must fit within available vertical clearance on the PCB.',
      sortOrder: 14,
    },
    {
      attributeId: 'safety_rating',
      attributeName: 'Safety Rating (UL/TUV)',
      logicType: 'identity_flag',
      weight: 7,
      engineeringReason: 'If original has UL or TUV safety rating, replacement must also have equivalent certification. Required for mains-connected applications.',
      sortOrder: 15,
    },
    {
      attributeId: 'aec_q200',
      attributeName: 'AEC-Q200 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Required for automotive applications. A non-qualified part cannot replace a qualified one.',
      sortOrder: 16,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'Tape & Reel required for automated pick-and-place. Ensure packaging matches production line requirements.',
      sortOrder: 17,
    },
  ],
};
