import { LogicTable } from '../types';

/**
 * Film Capacitors Logic Table
 * DigiKey Family ID: 64
 *
 * Derived from: docs/film_capacitors_logic.docx
 * 19 attributes with specific matching rules for cross-reference validation.
 */
export const filmCapacitorsLogicTable: LogicTable = {
  familyId: '64',
  familyName: 'Film Capacitors',
  category: 'Passives',
  description: 'Hard logic filters for film capacitor replacement part validation',
  rules: [
    {
      attributeId: 'capacitance',
      attributeName: 'Capacitance',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'Capacitance must match exactly. Ensure values are normalized before comparison.',
      sortOrder: 1,
    },
    {
      attributeId: 'voltage_rated_dc',
      attributeName: 'Voltage Rating (DC)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 9,
      engineeringReason: 'The replacement must handle at least the same DC working voltage. Higher is always acceptable.',
      sortOrder: 2,
    },
    {
      attributeId: 'voltage_rated_ac',
      attributeName: 'Voltage Rating (AC)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 8,
      engineeringReason: 'The replacement must handle at least the same AC voltage. Important for EMI filtering and motor run applications.',
      sortOrder: 3,
    },
    {
      attributeId: 'dielectric_type',
      attributeName: 'Dielectric Type',
      logicType: 'identity_upgrade',
      upgradeHierarchy: ['PP', 'PPS', 'PEN', 'PET'],
      weight: 7,
      engineeringReason: 'Polypropylene (PP) has lowest losses and best stability. PPS handles higher temps. PEN/PET are lower performance. Upgrading is safe (e.g., PET→PP).',
      sortOrder: 4,
    },
    {
      attributeId: 'tolerance',
      attributeName: 'Tolerance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 6,
      engineeringReason: 'A tighter tolerance is always acceptable. Common: ±20%(M), ±10%(K), ±5%(J), ±2.5%(H), ±1%(F).',
      sortOrder: 5,
    },
    {
      attributeId: 'package_case',
      attributeName: 'Package / Case',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'Package must match for PCB footprint compatibility. Film capacitors come in radial, axial, and SMD packages.',
      sortOrder: 6,
    },
    {
      attributeId: 'lead_spacing',
      attributeName: 'Lead Spacing / Pin Pitch',
      logicType: 'identity',
      weight: 8,
      engineeringReason: 'Lead spacing must match exactly for through-hole parts. Different spacing requires different PCB hole patterns.',
      sortOrder: 7,
    },
    {
      attributeId: 'self_healing',
      attributeName: 'Self-Healing',
      logicType: 'identity_flag',
      weight: 7,
      engineeringReason: 'Self-healing (metallized) film capacitors can survive localized dielectric breakdown. If original requires this, replacement must also be self-healing.',
      sortOrder: 8,
    },
    {
      attributeId: 'dissipation_factor',
      attributeName: 'Dissipation Factor (tan δ)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Lower dissipation factor means less energy lost as heat. Critical in high-frequency and resonant applications.',
      sortOrder: 9,
    },
    {
      attributeId: 'esr',
      attributeName: 'ESR',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Lower ESR is generally better. Exception: some snubber circuits require specific ESR.',
      sortOrder: 10,
    },
    {
      attributeId: 'dv_dt',
      attributeName: 'dV/dt Rating',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 6,
      engineeringReason: 'The replacement must handle at least the same voltage slew rate. Critical in snubber and pulse applications.',
      sortOrder: 11,
    },
    {
      attributeId: 'ripple_current',
      attributeName: 'Ripple Current',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 6,
      engineeringReason: 'The replacement must handle at least the same ripple current. Important for filtering applications.',
      sortOrder: 12,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temp Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 7,
      engineeringReason: 'The replacement must cover at least the full operating temperature range of the original.',
      sortOrder: 13,
    },
    {
      attributeId: 'height',
      attributeName: 'Height',
      logicType: 'fit',
      weight: 5,
      engineeringReason: 'Must fit within available vertical clearance on the PCB.',
      sortOrder: 14,
    },
    {
      attributeId: 'body_length',
      attributeName: 'Body Length',
      logicType: 'fit',
      weight: 5,
      engineeringReason: 'Must fit within available board space. Film capacitors can vary significantly in body size.',
      sortOrder: 15,
    },
    {
      attributeId: 'safety_rating',
      attributeName: 'Safety Rating (X/Y Class)',
      logicType: 'identity_flag',
      weight: 9,
      engineeringReason: 'If original has X or Y safety rating (e.g., X2, Y2), replacement must have same or better class. Required for mains-connected EMI filtering. Safety critical.',
      sortOrder: 16,
    },
    {
      attributeId: 'flammability',
      attributeName: 'Flammability Rating (UL94)',
      logicType: 'identity_flag',
      weight: 7,
      engineeringReason: 'If original requires UL94 V-0 rating, replacement must also have it. Required for safety compliance in many end products.',
      sortOrder: 17,
    },
    {
      attributeId: 'aec_q200',
      attributeName: 'AEC-Q200 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Required for automotive applications. A non-qualified part cannot replace a qualified one.',
      sortOrder: 18,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'Tape & Reel or ammo pack required for automated assembly. Ensure packaging matches production line requirements.',
      sortOrder: 19,
    },
  ],
};
