import { LogicTable } from '../types';

/**
 * Power Inductors Logic Table
 * DigiKey Family ID: 71
 *
 * Derived from: docs/power_inductors_logic.docx
 * 17 attributes with specific matching rules for cross-reference validation.
 */
export const powerInductorsLogicTable: LogicTable = {
  familyId: '71',
  familyName: 'Power Inductors (Surface Mount)',
  category: 'Passives',
  description: 'Hard logic filters for power inductor replacement part validation',
  rules: [
    {
      attributeId: 'inductance',
      attributeName: 'Inductance',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'Inductance must match exactly. A 10µH inductor must be replaced by a 10µH inductor. Ensure values are normalized before comparison.',
      sortOrder: 1,
    },
    {
      attributeId: 'package_case',
      attributeName: 'Package / Case',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'The replacement must match the original footprint exactly. Inductor pad geometries differ across sizes.',
      sortOrder: 2,
    },
    {
      attributeId: 'tolerance',
      attributeName: 'Tolerance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 6,
      engineeringReason: 'A tighter tolerance is always acceptable. Common: ±20%(M), ±10%(K), ±5%(J).',
      sortOrder: 3,
    },
    {
      attributeId: 'saturation_current',
      attributeName: 'Saturation Current (Isat)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 9,
      engineeringReason: 'The replacement must handle at least the same saturation current. Below Isat, inductance drops sharply (typically defined at 20-30% L drop). Insufficient Isat causes converter instability.',
      sortOrder: 4,
    },
    {
      attributeId: 'rated_current',
      attributeName: 'Rated Current (Irms)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 9,
      engineeringReason: 'The replacement must handle at least the same RMS current. Irms is the thermal rating — exceeding it causes excessive temperature rise.',
      sortOrder: 5,
    },
    {
      attributeId: 'dcr',
      attributeName: 'DC Resistance (DCR)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 7,
      engineeringReason: 'Lower DCR means less I²R loss and less heat. Critical for high-current power inductors. Directly impacts converter efficiency.',
      sortOrder: 6,
    },
    {
      attributeId: 'core_material',
      attributeName: 'Core Material',
      logicType: 'identity_upgrade',
      upgradeHierarchy: ['Metal Alloy', 'Metal Composite', 'Ferrite'],
      weight: 5,
      engineeringReason: 'Metal alloy/composite cores offer softer saturation and better thermal performance vs ferrite. Upgrade from ferrite to metal alloy is generally safe for power applications.',
      sortOrder: 7,
    },
    {
      attributeId: 'shielding',
      attributeName: 'Shielding',
      logicType: 'identity_upgrade',
      upgradeHierarchy: ['Shielded', 'Semi-Shielded', 'Unshielded'],
      weight: 8,
      engineeringReason: 'Shielded is best (contains magnetic field), Semi-Shielded is acceptable, Unshielded radiates. Downgrading shielding risks EMI compliance failures.',
      sortOrder: 8,
    },
    {
      attributeId: 'srf',
      attributeName: 'Self-Resonant Frequency (SRF)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 5,
      engineeringReason: 'Above SRF, the inductor behaves as a capacitor. Higher SRF ensures the inductor operates properly at the switching frequency.',
      sortOrder: 9,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temp Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 7,
      engineeringReason: 'The replacement must cover at least the full operating temperature range of the original.',
      sortOrder: 10,
    },
    {
      attributeId: 'height',
      attributeName: 'Height (Seated Max)',
      logicType: 'fit',
      weight: 5,
      engineeringReason: 'Critical for tight enclosures and low-profile designs. Power inductors vary significantly in height.',
      sortOrder: 11,
    },
    {
      attributeId: 'acr',
      attributeName: 'AC Resistance (ACR)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 4,
      engineeringReason: 'Lower AC resistance means less loss at the switching frequency. Important for high-frequency converters.',
      sortOrder: 12,
    },
    {
      attributeId: 'inductance_vs_dc_bias',
      attributeName: 'Inductance vs DC Bias',
      logicType: 'application_review',
      weight: 7,
      engineeringReason: 'Inductance drops as DC current increases. Different core materials have different L vs I curves. Ferrite has hard saturation; metal alloy has soft roll-off. Consult datasheets.',
      sortOrder: 13,
    },
    {
      attributeId: 'construction_type',
      attributeName: 'Construction Type',
      logicType: 'identity',
      weight: 4,
      engineeringReason: 'Construction (wound, multilayer, molded) affects electrical and thermal characteristics. Wound types have higher current; multilayer types are smaller but lower current.',
      sortOrder: 14,
    },
    {
      attributeId: 'aec_q200',
      attributeName: 'AEC-Q200 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Required for automotive applications. A non-qualified part cannot replace a qualified one.',
      sortOrder: 15,
    },
    {
      attributeId: 'msl',
      attributeName: 'Moisture Sensitivity Level',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 3,
      engineeringReason: 'MSL 1 (unlimited floor life) is best. Lower MSL number is less restrictive and always acceptable.',
      sortOrder: 16,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'Tape & Reel required for automated pick-and-place. Ensure reel width and pitch match feeder specs.',
      sortOrder: 17,
    },
  ],
};
