import { LogicTable } from '../types';

/**
 * Rectifier Diodes — Standard, Fast, and Ultrafast Recovery
 * Block B: Discrete Semiconductors — Family B1
 *
 * Derived from: docs/rectifier_diodes_logic.docx
 * 23 attributes with specific matching rules for cross-reference validation.
 *
 * Key differences from passive families:
 * - Uses AEC-Q101 (not AEC-Q200) for automotive qualification
 * - Recovery Category uses identity_upgrade with hierarchy: Ultrafast > Fast > Standard
 * - Configuration (pin/internal wiring) is a hard Identity gate
 */
export const rectifierDiodesLogicTable: LogicTable = {
  familyId: 'B1',
  familyName: 'Rectifier Diodes — Standard, Fast, and Ultrafast Recovery',
  category: 'Discrete Semiconductors',
  description: 'Hard logic filters for rectifier diode replacement part validation',
  rules: [
    {
      attributeId: 'recovery_category',
      attributeName: 'Recovery Category',
      logicType: 'identity_upgrade',
      upgradeHierarchy: ['Ultrafast', 'Fast', 'Standard'],
      weight: 10,
      engineeringReason: 'Recovery category reflects how quickly the diode stops conducting reverse current. Hierarchy: Ultrafast (<50ns trr) > Fast (50-500ns) > Standard (>500ns). Upgrading is allowed (faster is always safe); downgrading is not — a standard diode in a high-frequency switching supply causes massive reverse current pulses, power dissipation, and potential thermal failure.',
      sortOrder: 1,
    },
    {
      attributeId: 'vrrm',
      attributeName: 'Max Repetitive Peak Reverse Voltage (Vrrm)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 10,
      engineeringReason: 'Primary voltage specification. The maximum repetitive reverse voltage the diode can block without breakdown. Higher is always safe. Do NOT confuse Vrrm with Vdc — Vrrm covers repetitive pulsed reverse voltage.',
      sortOrder: 2,
    },
    {
      attributeId: 'vdc',
      attributeName: 'Max DC Blocking Voltage (Vdc)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 8,
      engineeringReason: 'Maximum continuous DC reverse voltage. Usually equal to or slightly lower than Vrrm. Relevant for circuits with sustained reverse bias such as reverse polarity protection.',
      sortOrder: 3,
    },
    {
      attributeId: 'io_avg',
      attributeName: 'Average Rectified Forward Current (Io)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 10,
      engineeringReason: 'Primary current specification. Maximum average forward current at a specified reference temperature. Higher is always acceptable. Compare at the same reference temperature (Tc or Ta).',
      sortOrder: 4,
    },
    {
      attributeId: 'vf',
      attributeName: 'Forward Voltage Drop (Vf)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 8,
      engineeringReason: 'Voltage across the diode when conducting. Lower is better — Vf determines conduction power loss (P = Vf x If). In low-voltage circuits (5V, 3.3V), Vf has an outsized impact on efficiency.',
      sortOrder: 5,
    },
    {
      attributeId: 'ifsm',
      attributeName: 'Max Surge Forward Current (Ifsm)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'Maximum non-repetitive peak forward current for a single half-sine pulse (8.3ms/60Hz or 10ms/50Hz). This is the startup/inrush current rating. Critical in capacitor-input filters and motor drives.',
      sortOrder: 6,
    },
    {
      attributeId: 'trr',
      attributeName: 'Reverse Recovery Time (trr)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 8,
      engineeringReason: 'The most critical switching characteristic. During trr the diode conducts reverse current, causing power loss, voltage spikes, and EMI. Standard: >500ns, Fast: 50-500ns, Ultrafast: <50ns. Faster is always better for switching but comes with a Vf trade-off.',
      sortOrder: 7,
    },
    {
      attributeId: 'qrr',
      attributeName: 'Reverse Recovery Charge (Qrr)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 7,
      engineeringReason: 'Total charge recovered during reverse recovery — a better indicator of switching loss than trr alone. Two diodes with the same trr can have very different Qrr depending on recovery waveform shape. Lower Qrr means lower switching losses.',
      sortOrder: 8,
    },
    {
      attributeId: 'recovery_behavior',
      attributeName: 'Recovery Behavior (Soft vs. Snappy)',
      logicType: 'application_review',
      weight: 6,
      engineeringReason: 'How abruptly reverse current stops during recovery. Snappy recovery generates high di/dt voltage spikes (V = L x di/dt) that can exceed ratings of nearby components and cause EMI. In circuits with significant parasitic inductance, snappy recovery can be destructive. Not all datasheets specify this parameter.',
      sortOrder: 9,
    },
    {
      attributeId: 'ir_leakage',
      attributeName: 'Reverse Leakage Current (Ir)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Current flowing when reverse-biased. Lower is better. Important in high-voltage applications (leakage x voltage = standby power), battery-powered circuits, and high-temperature environments where leakage increases exponentially.',
      sortOrder: 10,
    },
    {
      attributeId: 'cj',
      attributeName: 'Junction Capacitance (Cj)',
      logicType: 'application_review',
      weight: 4,
      engineeringReason: 'PN junction capacitance when reverse-biased. Irrelevant at 50/60Hz. At high-frequency switching (>100kHz), Cj contributes to switching losses and reverse current spikes. Flag for review if application operates above 100kHz.',
      sortOrder: 11,
    },
    {
      attributeId: 'configuration',
      attributeName: 'Configuration',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'Critical physical and functional constraint. Configurations: Single, Dual Common Cathode, Dual Common Anode, Dual Series (half-bridge), Bridge (4 diodes). Internal wiring determines pin connections — a common cathode dual cannot replace a common anode dual even if the package is identical.',
      sortOrder: 12,
    },
    {
      attributeId: 'package_case',
      attributeName: 'Package / Form Factor',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'Must match the PCB footprint. Common packages: SMD (SOD-123, SMA, SMB, SMC, DPAK, D2PAK, PowerDI), Through-hole (DO-41, DO-15, DO-27, DO-201, TO-220, TO-247). Package also determines thermal capability.',
      sortOrder: 13,
    },
    {
      attributeId: 'pin_configuration',
      attributeName: 'Pin Configuration / Polarity Marking',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'Incorrect polarity = reverse-biased diode in a forward-biased position = circuit failure. For multi-die packages, pin-to-function mapping varies between manufacturers. The tab/heatsink connection also matters — usually connected to the common pin.',
      sortOrder: 14,
    },
    {
      attributeId: 'rth_jc',
      attributeName: 'Thermal Resistance, Junction-to-Case (Rtheta_jc)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 6,
      engineeringReason: 'How effectively the diode transfers heat from junction to case. Lower is better. Dominant thermal metric for heatsink-mounted packages (TO-220, TO-247, DPAK). Tj = Tc + (Pd x Rtheta_jc).',
      sortOrder: 15,
    },
    {
      attributeId: 'rth_ja',
      attributeName: 'Thermal Resistance, Junction-to-Ambient (Rtheta_ja)',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'How effectively the diode transfers heat to surrounding air without a heatsink. Relevant for SMD packages and small through-hole packages relying on PCB copper for heat dissipation.',
      sortOrder: 16,
    },
    {
      attributeId: 'tj_max',
      attributeName: 'Max Junction Temperature (Tj_max)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'Maximum allowable junction temperature. Standard: 150C or 175C. Higher Tj_max provides more thermal headroom. A replacement with lower Tj_max may overheat in conditions the original survived.',
      sortOrder: 17,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temperature Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 7,
      engineeringReason: 'Ambient temperature range over which the device is rated. The replacement range must fully contain the original range. For automotive: -40C to +125C or +150C.',
      sortOrder: 18,
    },
    {
      attributeId: 'pd',
      attributeName: 'Power Dissipation (Pd)',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 6,
      engineeringReason: 'Maximum power the device can dissipate. If Vf, Io, and thermal resistance all meet their thresholds, Pd is implicitly satisfied — but it is a useful cross-check, especially for SMD packages.',
      sortOrder: 19,
    },
    {
      attributeId: 'aec_q101',
      attributeName: 'AEC-Q101 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Automotive qualification for discrete semiconductors. AEC-Q101 (not Q200 — Q200 is for passives). Includes HTRB, H3TRB, TC stress tests. A non-qualified part cannot replace a qualified one in automotive applications.',
      sortOrder: 20,
    },
    {
      attributeId: 'mounting_style',
      attributeName: 'Mounting Style',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'Surface mount vs. through-hole. Cannot interchange without PCB redesign. Within each: axial vs. vertical (different footprints, mounting hardware). Power pad packages require matching PCB pads for thermal path.',
      sortOrder: 21,
    },
    {
      attributeId: 'height',
      attributeName: 'Height (Seated Max)',
      logicType: 'fit',
      weight: 5,
      engineeringReason: 'Verify mechanical clearance. Through-hole axial diodes (DO-41) ~4-5mm. TO-220 ~15mm. SMD varies: SMA ~2.5mm, DPAK ~2.3mm, D2PAK ~4.4mm. Stacked PCBs, enclosures, and adjacent components constrain available height.',
      sortOrder: 22,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging (Tape & Reel / Tube / Bulk)',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'SMD requires Tape & Reel for automated pick-and-place. Through-hole: Ammo Pack for auto-insertion, Tube or Bulk for hand assembly. Mismatch halts production lines.',
      sortOrder: 23,
    },
  ],
};
