import { LogicTable } from '../types';

/**
 * Supercapacitors Logic Table
 * DigiKey Family ID: 61
 *
 * Derived from: docs/supercapacitors_logic.docx
 * 18 attributes with specific matching rules for cross-reference validation.
 */
export const supercapacitorsLogicTable: LogicTable = {
  familyId: '61',
  familyName: 'Supercapacitors (EDLC / Ultracapacitors)',
  category: 'Passives',
  description: 'Hard logic filters for supercapacitor replacement part validation',
  rules: [
    {
      attributeId: 'capacitance',
      attributeName: 'Capacitance',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'Capacitance must match exactly. Supercapacitors range from mF to thousands of Farads. Ensure values are normalized before comparison.',
      sortOrder: 1,
    },
    {
      attributeId: 'voltage_rated',
      attributeName: 'Voltage Rating',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 9,
      engineeringReason: 'The replacement must handle at least the same voltage. Exceeding the voltage rating permanently damages supercapacitors. Typical ratings are 2.5V, 2.7V, 3.0V, 5.0V.',
      sortOrder: 2,
    },
    {
      attributeId: 'technology',
      attributeName: 'Technology / Chemistry',
      logicType: 'identity_upgrade',
      upgradeHierarchy: ['Hybrid', 'EDLC'],
      weight: 7,
      engineeringReason: 'Hybrid supercapacitors combine EDLC with pseudocapacitance for higher energy density. Upgrading from EDLC to Hybrid is generally safe if other parameters match.',
      sortOrder: 3,
    },
    {
      attributeId: 'esr',
      attributeName: 'ESR',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 8,
      engineeringReason: 'Lower ESR is better for power delivery applications. ESR determines the maximum pulsed power capability and energy lost as heat.',
      sortOrder: 4,
    },
    {
      attributeId: 'peak_current',
      attributeName: 'Peak Current',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 6,
      engineeringReason: 'The replacement must handle at least the same peak current. Important for pulse power applications like backup power and regenerative braking.',
      sortOrder: 5,
    },
    {
      attributeId: 'leakage_current',
      attributeName: 'Leakage Current',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 6,
      engineeringReason: 'Lower leakage is better. Critical for energy harvesting and long-duration backup where self-discharge matters.',
      sortOrder: 6,
    },
    {
      attributeId: 'self_discharge',
      attributeName: 'Self-Discharge',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Lower self-discharge means longer energy retention. Measured as voltage drop over time. Critical for backup power applications.',
      sortOrder: 7,
    },
    {
      attributeId: 'package_case',
      attributeName: 'Package / Case',
      logicType: 'identity',
      weight: 8,
      engineeringReason: 'Package must match for mounting compatibility. Supercapacitors come in cylindrical, prismatic, and coin cell formats.',
      sortOrder: 8,
    },
    {
      attributeId: 'diameter',
      attributeName: 'Diameter',
      logicType: 'fit',
      weight: 5,
      engineeringReason: 'Must fit within the PCB footprint. Cylindrical supercapacitors vary significantly in diameter.',
      sortOrder: 9,
    },
    {
      attributeId: 'height',
      attributeName: 'Height',
      logicType: 'fit',
      weight: 5,
      engineeringReason: 'Must fit within available vertical clearance. Supercapacitors can be quite tall.',
      sortOrder: 10,
    },
    {
      attributeId: 'tolerance',
      attributeName: 'Tolerance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 4,
      engineeringReason: 'A tighter tolerance is always acceptable. Supercapacitors typically have wide tolerances: -20/+80% or ±20%.',
      sortOrder: 11,
    },
    {
      attributeId: 'cycle_life',
      attributeName: 'Cycle Life',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'More cycles is always better. Supercapacitors offer 100K-1M+ cycles vs batteries. Critical for frequent charge/discharge applications.',
      sortOrder: 12,
    },
    {
      attributeId: 'lifetime',
      attributeName: 'Lifetime / Endurance',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'Longer lifetime is always acceptable. Rated in hours at max temp and voltage. Electrolyte degradation is the primary wear-out mechanism.',
      sortOrder: 13,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temp Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 7,
      engineeringReason: 'The replacement must cover at least the full operating temperature range. Supercapacitor performance degrades significantly at temperature extremes.',
      sortOrder: 14,
    },
    {
      attributeId: 'cap_aging',
      attributeName: 'Capacitance Aging',
      logicType: 'application_review',
      weight: 5,
      engineeringReason: 'Capacitance degrades over time and cycles. The rate varies by technology and manufacturer. Review end-of-life capacitance for your application lifetime.',
      sortOrder: 15,
    },
    {
      attributeId: 'esr_aging',
      attributeName: 'ESR Aging',
      logicType: 'application_review',
      weight: 5,
      engineeringReason: 'ESR increases over time and cycles. The rate varies by technology. Review end-of-life ESR to ensure the replacement meets application requirements.',
      sortOrder: 16,
    },
    {
      attributeId: 'aec_q200',
      attributeName: 'AEC-Q200 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Required for automotive applications. A non-qualified part cannot replace a qualified one.',
      sortOrder: 17,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'Tape & Reel or tray required for automated assembly. Ensure packaging matches production line requirements.',
      sortOrder: 18,
    },
  ],
};
