import { LogicTable } from '../types';

/**
 * Tantalum Capacitors Logic Table
 * DigiKey Family ID: 59
 *
 * Derived from: docs/tantalum_capacitors_logic.docx
 * 17 attributes with specific matching rules for cross-reference validation.
 */
export const tantalumCapacitorsLogicTable: LogicTable = {
  familyId: '59',
  familyName: 'Tantalum Capacitors',
  category: 'Passives',
  description: 'Hard logic filters for tantalum capacitor replacement part validation',
  rules: [
    {
      attributeId: 'capacitance',
      attributeName: 'Capacitance',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'Capacitance must match exactly. Ensure values are normalized (µF) before comparison.',
      sortOrder: 1,
    },
    {
      attributeId: 'voltage_rated',
      attributeName: 'Voltage Rating',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 9,
      engineeringReason: 'The replacement must handle at least the same voltage. Tantalum capacitors are particularly sensitive to voltage stress — derating to 50% is common practice.',
      sortOrder: 2,
    },
    {
      attributeId: 'package_case',
      attributeName: 'Package / Case (EIA)',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'EIA case size (A/B/C/D/E/V) must match exactly. Different cases have different pad geometries.',
      sortOrder: 3,
    },
    {
      attributeId: 'capacitor_type',
      attributeName: 'Capacitor Type',
      logicType: 'identity_upgrade',
      upgradeHierarchy: ['Polymer', 'MnO2'],
      weight: 7,
      engineeringReason: 'Polymer tantalum offers lower ESR, higher ripple current capability, and benign failure mode vs MnO₂. Upgrading from MnO₂ to Polymer is generally safe.',
      sortOrder: 4,
    },
    {
      attributeId: 'tolerance',
      attributeName: 'Tolerance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 6,
      engineeringReason: 'A tighter tolerance is always acceptable. Common: ±20%(M), ±10%(K), ±5%(J).',
      sortOrder: 5,
    },
    {
      attributeId: 'esr',
      attributeName: 'ESR',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 7,
      engineeringReason: 'Lower ESR is better for power filtering and decoupling. ESR is specified at 100kHz typically.',
      sortOrder: 6,
    },
    {
      attributeId: 'ripple_current',
      attributeName: 'Ripple Current',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'The replacement must handle at least the same ripple current. Insufficient ripple rating causes excessive heating and early failure.',
      sortOrder: 7,
    },
    {
      attributeId: 'leakage_current',
      attributeName: 'Leakage Current',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Lower leakage current is better. Critical for battery-powered and low-power designs.',
      sortOrder: 8,
    },
    {
      attributeId: 'dissipation_factor',
      attributeName: 'Dissipation Factor',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Lower dissipation factor means less energy lost as heat. Important for high-frequency applications.',
      sortOrder: 9,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temp Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 7,
      engineeringReason: 'The replacement must cover at least the full operating temperature range of the original.',
      sortOrder: 10,
    },
    {
      attributeId: 'height',
      attributeName: 'Height (Seated Max)',
      logicType: 'fit',
      weight: 5,
      engineeringReason: 'Critical for tight enclosures and low-profile designs. A taller part may not fit.',
      sortOrder: 11,
    },
    {
      attributeId: 'surge_voltage',
      attributeName: 'Surge / Inrush Voltage',
      logicType: 'application_review',
      weight: 6,
      engineeringReason: 'Surge and inrush behavior varies significantly between tantalum types. MnO₂ types are more susceptible to surge failure. Review application-specific surge requirements.',
      sortOrder: 12,
    },
    {
      attributeId: 'failure_mode',
      attributeName: 'Failure Mode (Benign)',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'If original specifies benign (open-circuit) failure mode, replacement must also have it. Critical for safety — MnO₂ tantalums can fail short and ignite.',
      sortOrder: 13,
    },
    {
      attributeId: 'dc_bias_derating',
      attributeName: 'DC Bias Derating',
      logicType: 'application_review',
      weight: 6,
      engineeringReason: 'Tantalum capacitors can lose capacitance under DC bias, though less severely than MLCCs. Consult manufacturer derating curves.',
      sortOrder: 14,
    },
    {
      attributeId: 'aec_q200',
      attributeName: 'AEC-Q200 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Required for automotive applications. A non-qualified part cannot replace a qualified one.',
      sortOrder: 15,
    },
    {
      attributeId: 'msl',
      attributeName: 'Moisture Sensitivity Level',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 3,
      engineeringReason: 'MSL 1 (unlimited floor life) is best. Lower MSL number is less restrictive and always acceptable.',
      sortOrder: 16,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'Tape & Reel required for automated pick-and-place. Ensure reel width and pitch match feeder specs.',
      sortOrder: 17,
    },
  ],
};
