import { LogicTable } from '../types';

/**
 * NTC Thermistors Logic Table
 * DigiKey Family ID: 67
 *
 * Derived from: docs/thermistors_logic.docx
 * 15 attributes with specific matching rules for cross-reference validation.
 */
export const ntcThermistorLogicTable: LogicTable = {
  familyId: '67',
  familyName: 'NTC Thermistors',
  category: 'Passives',
  description: 'Hard logic filters for NTC thermistor replacement part validation',
  rules: [
    {
      attributeId: 'resistance_r25',
      attributeName: 'Resistance @ 25°C (R25)',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'R25 is the primary specification. Must match exactly. Common values: 10kΩ, 100kΩ. This sets the operating point of the measurement circuit.',
      sortOrder: 1,
    },
    {
      attributeId: 'b_value',
      attributeName: 'B-Value (B-Constant)',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'The B-value defines the R-T curve shape. Even small differences in B-value cause significant temperature measurement errors. Must match within tolerance.',
      sortOrder: 2,
    },
    {
      attributeId: 'rt_curve',
      attributeName: 'R-T Curve Matching',
      logicType: 'application_review',
      weight: 8,
      engineeringReason: 'The full R-T curve must be compared, not just R25 and B-value. Different thermistor materials can have the same R25 and B-value but diverge at temperature extremes. Consult R-T tables.',
      sortOrder: 3,
    },
    {
      attributeId: 'r25_tolerance',
      attributeName: 'R25 Tolerance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 6,
      engineeringReason: 'A tighter tolerance is always acceptable. Common: ±5%, ±3%, ±1%, ±0.5%. Determines accuracy of the temperature reading.',
      sortOrder: 4,
    },
    {
      attributeId: 'b_value_tolerance',
      attributeName: 'B-Value Tolerance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'A tighter B-value tolerance means a more predictable R-T curve. Common: ±3%, ±1%. Critical for precision temperature measurement.',
      sortOrder: 5,
    },
    {
      attributeId: 'package_case',
      attributeName: 'Package / Case',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'Package must match. NTC thermistors come in SMD chip, glass bead, epoxy coated, and probe formats. Different packages have different thermal response.',
      sortOrder: 6,
    },
    {
      attributeId: 'thermal_time_constant',
      attributeName: 'Thermal Time Constant',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 5,
      engineeringReason: 'Faster thermal response (lower time constant) is acceptable. Important for applications requiring quick temperature sensing.',
      sortOrder: 7,
    },
    {
      attributeId: 'dissipation_constant',
      attributeName: 'Dissipation Constant',
      logicType: 'application_review',
      weight: 5,
      engineeringReason: 'The dissipation constant determines self-heating error. Different values require different current limits in the measurement circuit. Must review for specific circuit design.',
      sortOrder: 8,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temp Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 7,
      engineeringReason: 'The replacement must cover at least the full operating temperature range of the original. NTC thermistors are selected specifically for their measurement range.',
      sortOrder: 9,
    },
    {
      attributeId: 'max_power',
      attributeName: 'Maximum Power',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 6,
      engineeringReason: 'The replacement must handle at least the same power dissipation. Important for inrush current limiting NTCs.',
      sortOrder: 10,
    },
    {
      attributeId: 'application_category',
      attributeName: 'Application Category',
      logicType: 'identity',
      weight: 5,
      engineeringReason: 'Temperature sensing NTCs and inrush current limiting NTCs have fundamentally different designs. They are not interchangeable.',
      sortOrder: 11,
    },
    {
      attributeId: 'height',
      attributeName: 'Height',
      logicType: 'fit',
      weight: 4,
      engineeringReason: 'Must fit within available vertical clearance on the PCB.',
      sortOrder: 12,
    },
    {
      attributeId: 'interchangeability',
      attributeName: 'Curve Interchangeability',
      logicType: 'identity_flag',
      weight: 7,
      engineeringReason: 'Some NTC thermistors are designed as interchangeable replacements with standardized R-T curves (e.g., Murata NCP series). If original uses an interchangeable type, replacement should match the same curve standard.',
      sortOrder: 13,
    },
    {
      attributeId: 'aec_q200',
      attributeName: 'AEC-Q200 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Required for automotive applications. A non-qualified part cannot replace a qualified one.',
      sortOrder: 14,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'Tape & Reel required for automated pick-and-place. Ensure packaging matches production line requirements.',
      sortOrder: 15,
    },
  ],
};

/**
 * PTC Thermistors Logic Table
 * DigiKey Family ID: 68
 *
 * Derived from: docs/thermistors_logic.docx
 * 15 attributes with specific matching rules for cross-reference validation.
 */
export const ptcThermistorLogicTable: LogicTable = {
  familyId: '68',
  familyName: 'PTC Thermistors',
  category: 'Passives',
  description: 'Hard logic filters for PTC thermistor replacement part validation',
  rules: [
    {
      attributeId: 'resistance_r25',
      attributeName: 'Resistance @ 25°C (R25)',
      logicType: 'identity',
      weight: 10,
      engineeringReason: 'R25 is the primary specification. Must match exactly. This determines the normal-state behavior of the circuit.',
      sortOrder: 1,
    },
    {
      attributeId: 'curie_temp',
      attributeName: 'Curie / Switch Temperature',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'The Curie temperature is where the PTC exhibits its sharp resistance increase. This is the fundamental switching point and must match for proper overcurrent or overtemperature protection.',
      sortOrder: 2,
    },
    {
      attributeId: 'rt_curve',
      attributeName: 'R-T Curve Matching',
      logicType: 'application_review',
      weight: 8,
      engineeringReason: 'The full R-T curve shape determines the switching behavior. Different PTC materials can have different transition slopes. Consult datasheets for the full curve.',
      sortOrder: 3,
    },
    {
      attributeId: 'r25_tolerance',
      attributeName: 'R25 Tolerance',
      logicType: 'threshold',
      thresholdDirection: 'lte',
      weight: 6,
      engineeringReason: 'A tighter tolerance is always acceptable.',
      sortOrder: 4,
    },
    {
      attributeId: 'package_case',
      attributeName: 'Package / Case',
      logicType: 'identity',
      weight: 9,
      engineeringReason: 'Package must match. PTC thermistors come in SMD chip, radial, and disc formats with different pad geometries.',
      sortOrder: 5,
    },
    {
      attributeId: 'max_voltage',
      attributeName: 'Maximum Voltage',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'The replacement must handle at least the same maximum voltage. Exceeding the voltage rating can cause PTC failure.',
      sortOrder: 6,
    },
    {
      attributeId: 'max_current',
      attributeName: 'Maximum Current',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'The replacement must handle at least the same maximum current during fault conditions.',
      sortOrder: 7,
    },
    {
      attributeId: 'max_power',
      attributeName: 'Maximum Power',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 6,
      engineeringReason: 'The replacement must handle at least the same power dissipation.',
      sortOrder: 8,
    },
    {
      attributeId: 'trip_current',
      attributeName: 'Trip Current',
      logicType: 'identity',
      weight: 8,
      engineeringReason: 'For resettable fuse PTCs, the trip current must match. This is the current at which the PTC transitions to high-resistance state.',
      sortOrder: 9,
    },
    {
      attributeId: 'hold_current',
      attributeName: 'Hold Current',
      logicType: 'threshold',
      thresholdDirection: 'gte',
      weight: 7,
      engineeringReason: 'For resettable fuse PTCs, the hold current is the maximum current that won\'t trigger a trip. Higher hold current is acceptable if trip current also matches.',
      sortOrder: 10,
    },
    {
      attributeId: 'operating_temp',
      attributeName: 'Operating Temp Range',
      logicType: 'threshold',
      thresholdDirection: 'range_superset',
      weight: 7,
      engineeringReason: 'The replacement must cover at least the full operating temperature range of the original.',
      sortOrder: 11,
    },
    {
      attributeId: 'height',
      attributeName: 'Height',
      logicType: 'fit',
      weight: 4,
      engineeringReason: 'Must fit within available vertical clearance on the PCB.',
      sortOrder: 12,
    },
    {
      attributeId: 'interchangeability',
      attributeName: 'Curve Interchangeability',
      logicType: 'identity_flag',
      weight: 7,
      engineeringReason: 'If original uses a standardized PTC curve, replacement should match the same standard.',
      sortOrder: 13,
    },
    {
      attributeId: 'aec_q200',
      attributeName: 'AEC-Q200 Qualification',
      logicType: 'identity_flag',
      weight: 8,
      engineeringReason: 'Required for automotive applications. A non-qualified part cannot replace a qualified one.',
      sortOrder: 14,
    },
    {
      attributeId: 'packaging',
      attributeName: 'Packaging',
      logicType: 'operational',
      weight: 2,
      engineeringReason: 'Tape & Reel required for automated pick-and-place. Ensure packaging matches production line requirements.',
      sortOrder: 15,
    },
  ],
};
