#!/usr/bin/env node
/**
 * Regenerate lib/services/atlas-reserved-attribute-ids.json.
 *
 *   npm run atlas:reserved-ids
 *
 * WHY THIS FILE EXISTS: scripts/atlas-ingest.mjs is the LIVE ingest path and
 * cannot import TypeScript, so it cannot read the logic tables directly. It
 * needs the set of attributeIds the matching engine scores on in order to
 * refuse them as raw storage keys (see RESERVED_ATTRIBUTE_IDS in
 * lib/services/atlasMapper.ts for the bug this prevents).
 *
 * The TS copy computes the set from the registry at runtime and is therefore
 * always current. This JSON is the .mjs copy's view of the same truth, and
 * __tests__/services/atlasReservedAttributeIds.test.ts asserts the two match —
 * so adding a family or a rule and forgetting to re-run this FAILS THE BUILD
 * rather than silently letting a scoring slot be reused as a raw key.
 *
 * Do not hand-edit the JSON.
 */
import { writeFileSync } from 'fs';
import { getAllLogicTables } from '../lib/logicTables';

const OUT = 'lib/services/atlas-reserved-attribute-ids.json';

const ids = [
  ...new Set(
    getAllLogicTables().flatMap((t) => (t.rules ?? []).map((r) => r.attributeId).filter(Boolean)),
  ),
].sort();

writeFileSync(
  OUT,
  JSON.stringify(
    {
      _comment:
        'GENERATED by scripts/gen-reserved-attribute-ids.mjs — do not hand-edit. ' +
        'Every attributeId the matching engine scores on. Consumed by scripts/atlas-ingest.mjs ' +
        '(which cannot import TS) so a rescued/unmapped value can never occupy a scoring slot. ' +
        'Pinned against the live registry by __tests__/services/atlasReservedAttributeIds.test.ts.',
      generatedFrom: 'lib/logicTables (getAllLogicTables)',
      count: ids.length,
      ids,
    },
    null,
    2,
  ) + '\n',
);

console.log(`Wrote ${OUT}: ${ids.length} reserved attributeIds across ${getAllLogicTables().length} families.`);
